### ISSUE TITLE
file upload exception should cancel file transfer and provide error feedback to client

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1003]
The front end waits until entire file is transferred before notifying of error. The server exception for max file size occurs very quickly and the front end shows the progress bar slowly going to 100% and then failing.

**Comment by kaladay** [comment]
Relates to PR #995 .

**Comment by jsavell** [comment]
I was unable to recreate this in either the student or admin submission upload dialogs.

**Comment by jsavell** [comment]
With a very large PDF (+100mb), it does take longer to fail and notify the user, but it is failing and notifying as soon as the XHR request completes.

I think we would have to do some sort of pre-upload check before actually  uploading to fail sooner.
