### ISSUE TITLE
creating submissions with CLI after custom actions created causes repeated custom action values on submission

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1014]

**Comment by StephanieVUGSC** [comment]
I don't know what CLI means, but after creating a new custom action I was not able to get it to repeat on new submissions.

**Comment by wwelling** [comment]
CLI is for Command Line Interface it is more of a developer prompt we created to generate many submissions. This creates some entities in a different manner than the application itself.
