### ISSUE TITLE
Ensure submission history disallows continuing a submission after it has been submitted

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1062]
Confirm and Submit a submission and then navigate to the history. Should not be able to continue the submission.

**Comment by StephanieVUGSC** [comment]
Acceptance removed.  The issue still occurs when you first log into Vireo and make a submission.   In the Confirmation page, if you click on View  Submission Status the submission will still be In Process and editable.  Once the page is refreshed it will go away.  However, on subsequent submissions it closes immediately.  Students will not be making more than one submission at a time so the fix needs to occur  immediately.
