### ISSUE TITLE
Uploading primary document on Admin Submission View not updating Active Document side box

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1088]

**Comment by StephanieVUGSC** [comment]
on 1/17/2019 the action was recorded on TDL test site. However, it only worked for submissions created today.  Older submission actions were not showing up in Submission Status box.  The status remained frozen from several days prior-- but the Action Log included the changes.

**Comment by jsavell** [comment]
" I went back to try to see what I was talking about, but I don’t see any problems now with newer or older submissions.  Please close."

Closing based on updated feedback from issue reporter.
