### ISSUE TITLE
In staff view, email options in Add Comment and Add Field must be replaced with Roles.

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1093]
As an administrator, it is inconvenient to copy/paste or type out email addresses in Add Comment or Add File in a submission.  Please return the Vireo 3 functionality where roles took place of email addresses where possible.  Several screens from Vireo 3 follow:

Roles are visible as prompts
![image](https://user-images.githubusercontent.com/35782552/47531058-18dfed80-d872-11e8-95c4-e35af5dbef3a.png)

Autocomplete allows quick selection of recipient
![image](https://user-images.githubusercontent.com/35782552/47531116-40cf5100-d872-11e8-8d31-90468398cbb8.png)

Autocomplete shows roles previously set up in Configurable settings
![image](https://user-images.githubusercontent.com/35782552/47531216-9277db80-d872-11e8-9c66-e1ad842ca514.png)

Email log of what was sent
![image](https://user-images.githubusercontent.com/35782552/47531183-76743a00-d872-11e8-9671-df2ed86332e9.png)

**Comment by StephanieVUGSC** [comment]
Note, this functionality already exists partially in Batch Comment/Email in Vireo 4.  Choices for To: and CC: are Student and Advisor, but nothing else.

**Comment by StephanieVUGSC** [comment]
May be blocked by 982, 1091, 1094, 1114

**Comment by jcreel** [comment]
Size for including Submitter, Organization, Assignee, and any input contact fields - similarly to the recipient list on email workflow rules.  This will accommodate  advisor roles and college roles, etc, if they have values with emails.  This also has to work for CC:.  Assume that will use strings like "Submitter" in the UI as you add them, and the backend will have to process this.
