### ISSUE TITLE
BUG=Unable to upload controlled vocabulary

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1110]
As an Administrator, Vireo is allowing me to select a csv file, and "confirm" the upload but the new file does not actually load.  The information of the old file remains and a 500 error with no details is produced.

**Comment by StephanieVUGSC** [comment]
This may be related to the very large default files for Colleges, Departments, and Majors.  I am unable to overlay or change those large files, but uploads to smaller lists will work.  
Please reduce the default vocabularies for these sets to 10 rows otherwise it may be very difficult for users to customize these vocabularies.

**Comment by jcreel** [comment]
Need to experiment with this and check the stacktrace for the 500 in the logs before sizing.

**Comment by StephanieVUGSC** [comment]
As of 1/29/2019, this is working again in TDL test server.
