### ISSUE TITLE
Only Administrator role should be able to edit Institution level settings

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1111]
Remove Institution settings from view for all roles except Administrator, or remove edit privileges for all roles except Administrator.    The Institution level is the default and should be "locked down" in some way so that it is never accidentally changed.

**Comment by jcreel** [comment]
Sized as a client side solution to disable interaction on the top "Institution" management widgets when not admin.

**Comment by StephanieVUGSC** [comment]
This function is only partially working in test-etd.tdl.org When logged in as a Manager, Institution in Organizations in not grayed out.  I am prevented from making changes in Manage Organization, but I am allowed to make changes to the Institution's Workflow and Email Rules.  Only Administrators should have permission to change settings at the Institution level.
