### ISSUE TITLE
Introduce a distinction between Status and State

### ISSUE THREAD

**Issue by jeremythuff** [TexasDigitalLibrary/Vireo#1122]
Currently the code bas has conflated the terminologies of status and state. There should be a functional distinction between these two entities. This will allow for the completion of #1123

**Comment by wwtamu** [comment]
@smutniak @cstarcher @jeremythuff this issue can be closed as there is a persistent entity [SubmissionStatus](https://github.com/TexasDigitalLibrary/Vireo/blob/main/src/main/java/org/tdl/vireo/model/SubmissionStatus.java) and it corresponding enumeration of [SubmissionState](https://github.com/TexasDigitalLibrary/Vireo/blob/main/src/main/java/org/tdl/vireo/model/SubmissionState.java).

The corresponding issue https://github.com/TexasDigitalLibrary/Vireo/issues/1123 can be resolved by implementing controller endpoints for CRUD operations in [SubmissionStatusController](https://github.com/TexasDigitalLibrary/Vireo/blob/main/src/main/java/org/tdl/vireo/controller/SubmissionStatusController.java).
