### ISSUE TITLE
initial package build of Vireo 4.x doesn't copy application.yaml into war file

### ISSUE THREAD

**Issue by bricas** [TexasDigitalLibrary/Vireo#1127]
I did the build as per the instructions:

`
mvn clean package -DskipTests -Dproduction -Dassets.uri=file:/opt/vireo/ -Dconfig.uri=file:/opt/vireo/config/
`

however, loading up the war file (with java -jar), it complains about $production$ not being a boolean.

I was able to copy `target/classes/application.yaml` to `src/main/resources/application.yaml`, rebuild, and have a working .war file.

**Comment by StephanieVUGSC** [comment]
related to #840
