### ISSUE TITLE
Not entering an orcid ID causes the profile to fail updating

### ISSUE THREAD

**Issue by misilot** [TexasDigitalLibrary/Vireo#114]
Hi,

I cannot update a profile when I do not specify an Orcid ID.

See the error below. I am running v3.0.5

Thanks! 

![orciderror](https://cloud.githubusercontent.com/assets/1446856/13610441/b95352f8-e52b-11e5-8f36-2fe2787ab976.png)

This is error in application.log: 
```
2016-03-08 12:43:50,738 WARN  ~ IO error occured while validating ORCID: Server returned HTTP response code: 500 for URL: http://pub.orcid.org//orcid-bio
```

**Comment by gadkrumholz** [comment]
Hi @misilot, you'll need to turn off validation for ORCID (in admin settings) or disable the field in that step; it's not enough to make it optional to turn off validation for it.

Does this make sense?

**Comment by misilot** [comment]
Here are the settings

![orcid settings](https://cloud.githubusercontent.com/assets/1446856/13620642/46209d66-e55f-11e5-8101-9b68a31b2446.PNG)

Does this control the vireosite/profile page? 
![verify personal information orcid](https://cloud.githubusercontent.com/assets/1446856/13620669/77d89d04-e55f-11e5-9494-75cd0d9f1df5.PNG)

**Comment by gadkrumholz** [comment]
If I remember correctly, I believe that the profile page is also verified by the same logic in code.

Validate ORCID: will make sure that the ORCID # typed in is in a valid ORCID format and that it exists through the ORCID API

Authenticate ORCID: will make sure that the ORCID # typed in matches the first and last name in a submission through the ORCID API.

If both are "Off", and the field is set to "Disabled" or "Optional" it shouldn't give you any validation errors when ORCID field is left blank by a student.

If this is not the case, I'll have to diagnose it on my end and it may be a real bug.

**Comment by misilot** [comment]
I will check again tomorrow on the system with Shibboleth enabled. As with Local Authentication I am not having the issue.

**Comment by misilot** [comment]
Hmm it seems to be working today correctly. Not sure what was up with it. Thanks!
