### ISSUE TITLE
Batch comment should be revisited 

### ISSUE THREAD

**Issue by jeremythuff** [TexasDigitalLibrary/Vireo#1150]
Currently batch comment email recipients include student and advisor.

Advisor, since it is represented by a dynamically CRUDable predicate, cannot be emailed at the batch level. 

This should be changed to interface in similar way to the comment functionality on the single submission view's add comment and add file fields. The auto complete options should be for Submitter, Assignee and Organization. Additionally this should support the free typing of email addresses.

**Comment by StephanieVUGSC** [comment]
Please proceed with developing this feature in Batch Comment/Email.  

"This should be changed to interface in similar way to the comment functionality on the single submission view's add comment and add file fields. The auto complete options should be for Submitter, Assignee and Organization. Additionally this should support the free typing of email addresses."

Email to Organization does not work presently, so just add the autocomplete option for now.
