### ISSUE TITLE
viero.xml file not well formed XML

### ISSUE THREAD

**Issue by vphill** [TexasDigitalLibrary/Vireo#116]
In trying to use metadata in the vireo.xml file export, I found that it doesn't seem to be well formed. 

It seems that a `<person>` tag is getting opened in the "Attachments" element but is getting closed bye a `</submitter>` tag. 

If you take a look at this section https://github.com/TexasDigitalLibrary/Vireo/blob/master/conf/formats/vireo.xml#L277-L296

You can see the opening of the `<person>` tag on L277 and it being closed with a `</submitter>` tag at L296

**Comment by gadkrumholz** [comment]
sure enough... thanks for reporting it. Did you want to do a PR for it?
