### ISSUE TITLE
Metadata_thesis.xml  in DSpace Simple export missing degree values

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1189]
In a 2/20/2019 download from test-etd.tdl  the Metadata_thesis.xml  in DSpace Simple export was missing values for thesis.degree.name   and thesis.degree.level 

![image](https://user-images.githubusercontent.com/35782552/54043978-7e82a580-4193-11e9-99db-041613aceec3.png)

**Comment by smutniak** [comment]
I'm seeing values for both of those fields if I select 'Degree' under 'Personal Information' when creating the submission.

This is a non required value.  Should we make it required?

**Comment by StephanieVUGSC** [comment]
Oh, does the field have to be marked as required in the workflow for the value to be in an .xml export?  If so, yes, it needs to be marked as required.

**Comment by smutniak** [comment]
degree field marked as required in branch feb-sprint-118-make-degree-field-required
