### ISSUE TITLE
Dublin_core.xml in DSpaceSimple export missing value of dc.date.issued

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1190]
In a 2/20/19 download from test-etd.tdl.org there are many missing values in the Dublin_core.xml  file of the DSPace Simple export. 

dc.date.issued did not come through.  This should be the date that the submission was placed into the Approval Status.   Specifically, the date is missing from this line:     <dcvalue element="date" qualifier="issued"></dcvalue>

**UPDATE 5/24/2019 - dc.date.issued should NOT be mapped to Approval Date.  It should be mapped to Graduation Semester, using YYYY-MM format**

**Comment by smutniak** [comment]
After clicking on the Faculty Review URL and clicking 'I approve this Application' I see a date in the field.
    
    <dcvalue element="date" qualifier="issued">03/11/2019</dcvalue>

If I go back and unapprove the application then the date text in the xml element disappears.
Is this as expected?

**Comment by StephanieVUGSC** [comment]
No, I don't think this is related to the faculty Review actions.  This approval is one of the submission statuses like Corrections Received.  A date should be stamped when the staff changes the status to Approved.

**Comment by StephanieVUGSC** [comment]
UPDATE 5/24/2019 - dc.date.issued should NOT be mapped to Approval Date.  It should be mapped to Graduation Semester, using YYYY-MM format

**Comment by smutniak** [comment]
setting dc.date.issued to graduation YYYY-MM in file src/main/resources/formats/dspace_simple_dublin_core.xml would make it the same as dc.date.created, is that as expected?

**Comment by StephanieVUGSC** [comment]
Yes, as expected. They are the same date, but expressed in different formats.     

From metadata dictionary the primary date associated with a thesis is "defined as the date the student graduates or the date the degree is conferred, expressed in YYYY‐MM format. Encode this date in the <dc.date.issued> element.   Optional practice: A natural language version of the graduation date may be supplied in the <dc.date.created> element.   Date values are set up in the Vireo System (e.g. May or December)."

**Comment by smutniak** [comment]
To clarify, there are 3 distinct locations for that same date;
dc.date.created is expressed as YYYY-MM   (e.g. 2019-06)
dc.date.submitted is expressed as month YYYY   (e.g. June 2019)
dc.date.issued is expressed as YYYY-MM (e.g. 2019-06)


dc.date.issued is identical in date and format to dc.date.created but expressed in a different format than dc.date.submitted, correct?

**Comment by StephanieVUGSC** [comment]
dc.date.submitted can be removed from the Dublin_core.xml export.  The date submitted has no meaning to the library so it is not a supported field for cataloging.  It's just important for graduation requirements of submitting on time.    

That leaves us with dc.date.created  and dc.date.issued which are identical in date but expressed in different formats. 

<dc.date.created>December 2004</dc.date.created>
<dc.date.issued>2004‐12</dc.date.issued>
