### ISSUE TITLE
Flagged fields are no longer visible in staff View

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1193]
At some point a new section for "Flagged Fields" was added just below the Custom Actions box in the View tab for staff.  I marked a First Name field to be flagged, but it did not show up in the the box.  See submission 70 in test-etd.tdl and the Organization workflow named "Thesis" which is a child of Submission Type.

**Comment by cstarcher** [comment]
After further discussions with @StephanieVUGSC, it was decided that the Flagged Fields should be read-only.
