### ISSUE TITLE
Bug - ProQuest Release displays in Submission Status when hidden

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1196]
When the field profile for Proquest Publication is marked disabled or hidden, it should not appear in the Submission Status box of an associated submission.  
The example in the image is from submission 72 in test-tdl
![image](https://user-images.githubusercontent.com/35782552/54232201-27087080-44d8-11e9-8b74-c388562f3681.png)

**Comment by cstarcher** [comment]
After further discussions with @StephanieVUGSC, it was decided to remove Proquest Release from the Submission Status sidebox and reveal it in the Flagged Fields sidebox for consistency.

**Comment by jcreel** [comment]
The current code for this works, except that it will still show up under flagged fields if the field profile is both "flagged" and "hidden"
