### ISSUE TITLE
Second "SUBMISSION_URL"

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1220]
There is a second "SUBMISSION_URL" at the very bottom of the Properties in Email Templates.  After testing, it appears to work the same as the first one listed.   Please remove when possible.

![image](https://user-images.githubusercontent.com/35782552/55011474-e9b1e180-4fb3-11e9-870c-f2ca5f7ed244.png)

**Comment by StephanieVUGSC** [comment]
Please link to 1224

**Comment by cstarcher** [comment]
relates to #1224
