### ISSUE TITLE
Add info text to ProQuest Settings indexing setting

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1226]
In Workflow Management ProQuest Settings tab, the info circle for Indexing has text "todo"
![image](https://user-images.githubusercontent.com/35782552/55262382-a79ad100-523b-11e9-9bef-7de02b494ec4.png)

Please replace text with  "If enabled, all submissions to ProQuest will have their citations indexed by third parties such as Google and Educational Resources Information Center(ERIC). "

**Comment by cstarcher** [comment]
Resolved #1559
