### ISSUE TITLE
Add Vireo 3 functionality to batch email Advisors

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1231]
Emailing Advisors in batch is a critical function for Vireo users.   Please hard-code an option for Advisor that would look for any field profile with the "dc.contributor.advisor" predicate.  

 Users will be instructed not to change the predicate or make the field unavailable in a workflow, with warning that otherwise the batch email to advisor will not work. 

In keeping with Vireo 3 functionality, we will also instruct users to not make this field repeatable so that only 1 email address is allowed.

**Comment by smutniak** [comment]
Should this be implemented by adding an 'Advisor' option to the Batch Comment/Email intermodal 'To' field along with Assignee and Submitter?  Would advisor specifically be Committee Chair?
