### ISSUE TITLE
A deleted field profile cannot be recreated

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1233]
Vireo 4 will not allow the re-creation of deleted field profile.   When attempting to Create/Save the new field profile and error message about the field predicate already exists, even if it not in the current workflow.

**Comment by StephanieVUGSC** [comment]
The field profile will return when selecting "Sync with Parent" so perhaps manually adding a deleted field profile was not intended to be an allowable action.

**Comment by rladdusaw** [comment]
If you want to avoid syncing the entire organization, you can go to the parent organization and set the field profile to non-overridable and then back to overridable.  This will re-create the field profile on the child organization.

**Comment by StephanieVUGSC** [comment]
The workaround only provided a partial solution.  When I changed the parent field profile to non-overridable, the missing field reappeared in the child workflow step.  However, I was not able to change the parent field profile back to overrideable.  error message  is " FieldProfile with fieldPredicate of org.tdl.vireo.model.FieldPredicate@36, fieldPredicate of org.tdl.vireo.model.FieldPredicate@36 and overrideable of true already exists."

**Comment by cstarcher** [comment]
Only occurs with default field profiles with more than one word in name

**Comment by kaladay** [comment]
The referenced pull request #1504 claims this as resolved.
