### ISSUE TITLE
mixed content delivered by vireo4 not rendered under https in certain browsers

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1235]
This 'mixed content' is handled differently by different browsers.

brave - doesn't care - renders the http and https pages properly.

chrome - doesn't care - renders the http and https pages properly.

safari - will render the http page properly but not the https page.  (see image at bottom) It will show the page as in the image.  I didn't look hard but have not found a way to get safari to ignore mixed content warnings.

firefox - will render the http page properly but not the https page (results same as safari image).  Firefox will show a circle favicon with an 'i' inside just to the left of the lock symbol.  Clicking on it will allow a user to permit mixed content, but the site is no longer considered secure as indicated by red slash through lock icon.

To make sure this was not an issue of the deployment/hosting/AWS quirks, I built the jar file in a docker container, deployed on a digital ocean droplet, and used an nginx proxy instead of the typical apache proxy.  It appears the vireo build (as a jar or war) is causing this mixed content problem which certain browsers notice.
<img width="1176" alt="mixed_content" src="https://user-images.githubusercontent.com/1197715/56923377-ff716580-6a8f-11e9-924d-e71e68ed829a.png">

**Comment by smutniak** [comment]
Try on https://test-etd-clone.tdl.org/
If you work on this please contact me via slack and I'll get you the credentials and info for signing into test-etd-clone.tdl.org

**Comment by shoutinblues** [comment]
I'm finding Chrome displays the errant page by default.  At the right of the location bar is a shield with a red X.  When I click on the shield, it gives the option to "load unsafe scripts."  Doing so allows the page to load as intended.  I'm using Chrome Version 76.0.3809.132 (Official Build) (64-bit) on Windows 7.  Chrome developer tools says, "Mixed Content: The page at 'https://vireo4-test.library.uta.edu/' was loaded over HTTPS, but requested an insecure stylesheet 'http://vireo4-test.library.uta.edu/wro/app.css'. This request has been blocked; the content must be served over HTTPS."

**Comment by smutniak** [comment]
resolved long ago - url: setting in application.yaml.  There are also more minor glyph issues which show up as a CORS issue on local development computer if mixing '127.0.0.1' and 'localhost' as expressed in the browser vs application.yaml
