### ISSUE TITLE
Change metadata keys

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1236]
The Metadata key for "school"  in the Workflow Management tab should be thesis.degree.school  and "program" should be  thesis.degree.program

**Comment by smutniak** [comment]
I see a 'school' at position 8 but I don't see a 'program' anywhere in the list.  Is this issue based on an old list?

**Comment by StephanieVUGSC** [comment]
No this is a new issue.  I didn't realize we had a problem until comparing our metadata keys with the the MetaData Working Group report.  "school" in position 8 needs to change to thesis.degree.school.   It should also be changed in the field profile for "school" in the Personal Info workflow step. 

The metadata key initially assigned to Program was theses.degree.discipline, which is incorrect in this context and why you do not see Program in the list of metadata keys.   We need a new key of thesis.degree.program added that should be assigned to the "program" field profile in the Personal Info workflow step. 

thesis.degree.discipline should be removed as a metadata tag.  It would be valid only if we had a field profile called Discipline.  This is more for descriptive cataloging and not something a student would know for certain since it would overlap with their department, college, or major.
