### ISSUE TITLE
Remove dc.date.issued from Defense Date Field Profile

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1260]
The dc.date.issued metadata key as defined in the “Dictionary of Texas Digital Library Descriptive Metadata for Electronic Theses and Dissertations, v.2” https://tdl-ir.tdl.org/handle/2249.1/68437  is the Graduation Date expressed in YYYY-MM format.  It is not the defense date. 

Please create a non dublin core metadata tag such as "defense_date" for this field profile.

**Comment by jcreel** [comment]
Change the Graduation Date FP to use the dc.date.issued predicate.  Make sure formatters and exporters interpret dc.date.issued as a graduation date.

In addition, use a new predicate for the Defense Date FP (don't use dc.date.issued there).  Double check for any places the Defense Date needs to be formatted/exported.
