### ISSUE TITLE
User Preferences are not saved  in Profile

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1266]
Selecting checkboxes in the Preferences section of Profile do not stick. 

![image](https://user-images.githubusercontent.com/35782552/58040779-f9edc500-7afb-11e9-9b38-537bb51b3453.png)

**Comment by StephanieVUGSC** [comment]
This feature is especially important for admins who need to be copied on all emails sent by the system on their behalf.

**Comment by kaladay** [comment]
The pull request #1421 claims this is resolved.
