### ISSUE TITLE
Admin Settings -> Application Settings -> Submission Availability has "todo" in help

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1271]
The "Current Submission Semester" and "Degree Granting School" inputs have **todo** instead of some description for the help icon popup.

**Comment by cstarcher** [comment]
Degree Granting School should have the following popup text:

The full name of the institution awarding the degrees.

Current Submission Semester should have the following popup text:

Month Year (e.g. May 2020)
