### ISSUE TITLE
Unable to delete file type due to restrictions, despite the file type not being used

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1279]
Under _Admin Settings -> Workflow Management -> File Types_.

After adding a new file type and then immediately attempting to delete it, I get the error:
`Unable to delete due to restrictions! FieldValue fieldPredicate.documentTypePredicate cannot be true!`.

To reproduce this:
Create a submission and attach a file to that submission (such as the primary document (Manuscript in PDF).
Navigate to _Admin Settings -> Workflow Management -> File Types_.
Add a new File type.
Delete the newly added file type.

The error goes away if I remove the document attached to the submission.
The error goes away if I delete the submission with the document attached.

I would note that the new file type is not used.
It appears that if any Submission has a file type uploaded, then no file type may ever be deleted.

**Comment by wwelling** [comment]
https://github.com/TexasDigitalLibrary/Vireo/blob/master/src/main/java/org/tdl/vireo/model/repo/impl/DocumentTypeRepoImpl.java#L22

https://github.com/TexasDigitalLibrary/Vireo/blob/master/src/main/java/org/tdl/vireo/model/FieldPredicate.java#L39

Creating a document type is always setting the field predicate documentTypePredicate property to false.

**Comment by wwelling** [comment]
https://github.com/TexasDigitalLibrary/Vireo/blob/master/src/main/java/org/tdl/vireo/controller/DocumentTypeController.java#L59

This business validation does not meet this use case. It performs a join with all field values and checks the results for a specific value match.

The validation will have to join with field values where the document type field predicate matches the field value field predicate. This is currently not supported by weaver validation.
