### ISSUE TITLE
BUG: Customize Filters deletes fields when attempting to move them

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1300]
Customize filters is no longer working correctly.  I am unable to place fields in the desired order in the Display column.  When I attempt to drag and drop, the field disappears .  In addition, the field will disappear from List View even if did not click Save when exiting the window.   If possible, please fix by Launch.

**Comment by StephanieVUGSC** [comment]
Workaround:  Remove all filters, then click on the names in the right column in the order in which they should appear.  Do not drag and drop.

**Comment by kaladay** [comment]
Recent changes to the filters may have reslolved this.
