### ISSUE TITLE
DSpace Simple export fails on CLI generated submissions

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#1317]
java.text.ParseException: Unparseable date: "2015-03-10"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at org.tdl.vireo.utility.SubmissionHelperUtility.getGraduationMonthYearString(SubmissionHelperUtility.java:324)
	at org.tdl.vireo.model.formatter.DSpaceSimpleFormatter.populateContext(DSpaceSimpleFormatter.java:65)

**Comment by smutniak** [comment]
The date string in dc.date.created is of the form "01/06/2015" if Cli.java's generate is used.
If the UI is used to create a submission then dc.date.created stores a string for the ISO date such as "2019-12-01T06:00:00.000Z" 

Additionally, a submission without a Primary document will fail on DSpace export.  A primary document is needed before a submission can pass the checklist in Confirm and Submit.  The export will still work if 'Confirm and Submit' has not been done as long as it has what it needs to be submitted.  (Lacking the required 'Degree Name' didn't cause problems for an export though.)

**Comment by kaladay** [comment]
There have been changes to how dates are stored.
This issue should be revisited.
