### ISSUE TITLE
Global Embargos and display bug

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1328]
Changing Global (System) ProQuest Embargoes to Display = No, did not work.   (related to #1269).  Not only did the edit not save, but Vireo also created a copy of the embargo.   The copy saved as Display = No, but still displayed in student and staff views.
 
![image](https://user-images.githubusercontent.com/35782552/61150666-99e71f80-a4a9-11e9-939e-a19faaf93567.png)

This is the staff side submission view, but it is the same as what was visible in student view. 
 
![image](https://user-images.githubusercontent.com/35782552/61150683-9d7aa680-a4a9-11e9-9915-b3b77bd73e87.png)

**Comment by jcreel** [comment]
Also need to add a filter to not show the non-displayable ones in the Embargo input types.
