### ISSUE TITLE
When editing name on org for the first time, soon after typing begins, the input field is refreshed/replaced from persisted value.

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#1334]
This loses whatever typing was done. Happens once whenever editing name on an org on a fresh page load or first time navigation to that org in the settings.

Update from Aug 16 - unable to reproduce in Firefox during sizing meeting.  Possibly a race condition related to broadcasts - try with multiple browsers open?

**Comment by jsavell** [comment]
I wasn't able to recreate the problem described in the title in any major browser.

The only similar issue I was able to find was by opening two different tabs/browsers to simulate multiple admins editing at the same time. 

From there, if you start editing the organization name in one, then edit and save in the other, the initial in progress edit from the first window is reset by the broadcast from the other save.
