### ISSUE TITLE
No validation on color fields Look and Feel

### ISSUE THREAD

**Issue by gerrut** [TexasDigitalLibrary/Vireo#1336]
A colleague changed the color of the application in 'Application Settings'->'Look and Feel', but made an incomplete copy of the value leaving out the last digit. This tiny error meant the css did not compile and the lay-out fell apart, making it difficult to switch the setting back. Is it possible to add validation to the field so it only accepts a full valid hex with length of six?

**Comment by jcreel** [comment]
Add front-end validation
