### ISSUE TITLE
Security issue? Registration activation link can be used on other servers

### ISSUE THREAD

**Issue by gerrut** [TexasDigitalLibrary/Vireo#1337]
After registering an email for a new user account, you receive a confirmation link after which you can setup the user account.
This registration link does not have any connection to the website where the user tried to register. In other words, the link for my local environment, worked perfectly to create a new account on a clean install and on the Texas test server. 
I am unsure if this is a bug or still working once you have a production server with Shibboleth, but it struck me as a possible security issue.

**Comment by jcreel** [comment]
This can be addressed by changing the default secret in the application.yaml.  This needs to be addressed in the documentation.
