### ISSUE TITLE
Models force-closed on broadcast become out of date

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1362]
When an open model is force-closed because it was recently updated and a broadcast was received, the `$dirty` state of that model may end up being set to TRUE.
When this happens, the data that model was representing will be out of date and the display of that data will be out of date. This is misleading.

Either don't close the modal and report that it is now out of date or when the modal is force-closed, reset the data that model represents to the updated data provided by the broadcast.

To reproduce this, open two separate windows on say Admin List -> Settings -> Workflow Management -> Embargo Types.
Open an edit modal for Default Embargoes "None" in both windows.
Make a change and save it in one window.
The models in both windows should close at the same time.
Re-open the models in both windows.
The console log in the window where the edit was *not* made will have something like `abstractRepo.js:407 UPDATE attempted on dirty model Embargo {…}`.
The modals on both screen are now inconsistent.
(Sometimes this has to be repeated a couple of times to reproduce, but usually by the second time the problem shows up.)

This issue can be better observed when editing a custom Default Embargo, such that the description is changed when the models are open. The "Description" in each window will become incorrect, presenting incorrect information to the user.

**Comment by cstarcher** [comment]
This is fixed as of 4.2.6.
