### ISSUE TITLE
"Review Application", 401 error when not logged in

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1365]
The "Review Application" path allows for one to view the page with a valid hash without otherwise having access to the system.
The problem is that when a user is not actually logged in, the `ERROR: (401) You are not authorized for request ` is improperly presented.
The error should not be presented in this case or the access credentials should not be checked at this path.

**Comment by kaladay** [comment]
I have observed this error even when logged in with a user whose role is `ROLE_ADMIN`.
The error appears but I can still view the page!

The console network log shows 401 for: `http://localhost:9000/settings/embargo/all` for anoynmous and for user with `ROLE_ADMIN`.

The error happens on `embargo` so it may be worth checking to see if this is related to the following:
- #910
- #1362
- #1364

**Comment by cstarcher** [comment]
I have replicated this error. It is not related to Issue #910.

**Comment by smutniak** [comment]
I know that SHSU and UTSWMED both reported the embargoes not showing up in some but not all student's views and it had to be manually remedied by an admin which sounds like 910.  Were you able to replicate 910?

**Comment by smutniak** [comment]
nevermind, i see you fixed 910 elsewhere.
