### ISSUE TITLE
{SUBMISSION_ASSIGNED_TO} and other values not being templated in emails sent through admin interface

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#1373]
Relates to #1225

**Comment by StephanieVUGSC** [comment]
These are working for me.  
![image](https://user-images.githubusercontent.com/35782552/65063818-a1f98a80-d944-11e9-8199-d1e47f5d799f.png)

**Comment by cstarcher** [comment]
SUBMISSION_ASSIGNED_TO is populated when present in 4.2.6.
