### ISSUE TITLE
Edit HTML instructions for licenses, etc

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1381]
HTML tags do not appear to be supported where indicated.  Please remove the following sentence from the bottom of text boxes in Look & Feel, Submission License, and ProQuest settings:

"The following HTML tags are allowed: h1 - h5, p, a, b, i, u, ol, li, img."

**Comment by smutniak** [comment]
This refers to the small font grey text beneath each textarea under Settings > Application > LOOK AND FEEL

It should align with what html elements may actually be used in those text areas, either by changing the text or correcting the text area.
