### ISSUE TITLE
Manage Users page (as admin) not performant - eager fetching server side component

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1387]
Listing a few hundred users via the 'Manage Users' menu option for someone with admin role takes a few seconds to render (utswmed with 731) but larger amounts ( ttu with 5426 or uh with 4652) consume browser resources to the point of not rendering after many minutes - browsers (firefox and chrome) will ask to stop or wait on the javascript consuming resources.

the websites mentioned have migrated data
https://utswmed-migrate-etd.tdl.org
https://ttu-migrate-etd.tdl.org
https://uh-migrate-etd.tdl.org

**Comment by smutniak** [comment]
This ticket is focused on the server side eager fetching component

**Comment by rladdusaw** [comment]
The cause of the slowdown on the User management page was found to be the UI having trouble processing all the user at one time. Pagination of the users was sufficient to resolve the problem and lazy fetching of Users was no longer necessary.
