### ISSUE TITLE
Home link in submission history should be configurable 

### ISSUE THREAD

**Issue by dgonz77** [TexasDigitalLibrary/Vireo#1391]
Home link in the breadcrumb is hard coded to the root site.  

```
<ul class="breadcrumb">
     <li><a href="/">Home</a></li>
      <li class="active">Submissions</li>
</ul>
```
if vireo is running on a sub path this address is not correct. This should be configurable through the UI or static configurations.

**Comment by mtpatterson** [comment]
Do we even need this as a link since the header has a hyperlink to the base URL?

**Comment by cstarcher** [comment]
Use base href to configure on build

**Comment by wwelling** [comment]
https://stackoverflow.com/questions/7578620/anchor-a-link-to-base-url

Just need to change the href to relative path to base. `href=""` or `href="."`

**Comment by jcreel** [comment]
Issue requestor @dgonz77 agrees that linking to the base deployment path is acceptable.
