### ISSUE TITLE
Results vary when ancestor is changed to "Override = No" in ancestor 

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1393]
If a subordinate has "Workflow Step is Overridable" set to No and the ancestor changes the same Workflow Step from yes to "Workflow Step is Overridable" = No, the results will vary.  
Sometimes the subordinate will become Read Only, but not necessarily inherit the current ancestor settings.  Other times it does not become Read Only and retains its settings.

**Comment by cstarcher** [comment]
The inconsistency I see here is with inheritance from a parent. When a parent field profile is set to "Overridable: No" the same field profile on the child is editable until page refresh. If the page is not refreshed and an attempt to edit or delete the child field profile is made, it doesn't work. Also, when parent field profile is set to "Overridable: Yes" it does not update the child field profile until page refresh.

It seems maybe isEditable is not being bound until page refresh.

**Comment by kaladay** [comment]
The pull request #1504 claims to have resolved this.

**Comment by cstarcher** [comment]
Unable to reproduce in version 4.2.6.
