### ISSUE TITLE
Possible bug with Field Profiles and Overridable setting

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1394]
Changing a Field Profile from “Override = Yes” to “Override = No” on descendant 1 will prevent descendant 2 from changing “Override = Yes” to “Override = No” in same Field Profile.  It will also prevent the Ancestor from changing “Override = Yes” to “Override = No” in same Field Profile.

**Comment by cstarcher** [comment]
Possibly relates to #1393

**Comment by cstarcher** [comment]
The first part of this issue is fixed. The second part, if I'm understanding it correctly, is the same issue as #1393. I will go ahead and close this issue and leave #1393 open.

**Comment by kaladay** [comment]
This issue is supposed to be closed as per comment above but is not in fact closed.
