### ISSUE TITLE
BUG - Reordering Default Embargoes does not display in submission view

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1398]
Reordering of global Default Embargoes in settings does not show up in student Submission View.  Unlike custom embargoes, the global (system default) Embargo types can be reordered in the Settings, but they will not appear in the new order in new student submissions.

**Comment by smutniak** [comment]
I'm looking at the Document Information page while signed in as a student and I see no embargoes listed (default or proquest) and I see an error message in firefox web dev console:

TypeError: "embargo is null"
    sortEmbargos studentSubmissionController.js:134
    orderVocabularyWords fieldProfileDirective.js:377
    Angular 10
        predicateValues
        a
        Sd
        fn
        d
        $digest
        $apply
        t
        completeTask
        d
angular.js:15536:15
    Angular 7

**Comment by jsavell** [comment]
I corrected the embargo order for the view when the student is creating a new submission but missed this other view. Updating it now.
