### ISSUE TITLE
BUG - Custom embargoes cannot be reordered 

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1399]
Related to 1398
We can create custom embargoes (in Default Embargo settings) but the system will not allow drag and drop to reorder them.  There appears to be no problem with reordering the global (or system) embargoes. 

This behavior is inconsistent.  Sometimes reordering custom embargoes will work, but still do not display in the new order in student submission view.

**Comment by smutniak** [comment]
Under Settings > Workflow Management > Embargo Types one can create a custom embargo type.
I was able to move my embargo once I called 'Sort Default by Duration.'
The first try I could not delete my embargo.  On subsequent tries I could.

**Comment by smutniak** [comment]
The behavior of embargo drag and drop is actually very consistent.  Dragging an item moves it but the other items on the list do not part to make a space for dropping it unless the 'mouse down' button (i'm using a trackpad) is lifted.

If the drag has already started then the movement of the item with one finger on the trackpad continues.  Dropping it with a 'mouse click' puts it into place.  The promise in main/webapp/app/repo/embargoRepo.js will then call the '/reorder/{guarantorString}/{src}/{dest}' method in java/org/tdl/vireo/controller/EmbargoController.java

There may be some angular directive in main/webapp/app/views/directive /dragAndDropTable.html and its setting of isMouseHover that will fix this, but I am stuck figuring it out.  If there is someone more angularjs familiar than me (which should be anyone) with any advice I'd be happy to hear it.

**Comment by smutniak** [comment]
I also noticed - If I hold down the option key on a mac and then try to operate drag and drop it
behaves as expected. I presume this would be the ALT key on windows and linux.

**Comment by StephanieVUGSC** [comment]
The ALT key does work to reorder the embargos in the Workflow Settings.  Now the problem is that it does not display in the student submission screen.  I tried making a new workflow, then I made a new organization and neither of them would display the embargoes as they were reordered.
