### ISSUE TITLE
Field profile cannot be moved to another workflow step

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1413]
I am unable to remove a field profile from one workflow step so that I can place it in another.  The field profile can be deleted, but it cannot be added to the new workflow step, nor can it be recreated in the old workflow step without attempting to sync with parent, which is not working, see #1233.

**Comment by cstarcher** [comment]
Only occurs with default field profiles with more than one word in name

**Comment by cstarcher** [comment]
Unable to reproduce in version 4.2.6.
