### ISSUE TITLE
Add Vireo 3 feature where Custom Actions display in the order they were placed in the settings

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1429]
As a manager, I need to be able to control the order of the Custom Actions.  Custom actions are global settings that cannot be customized by workflow.  They are used by multiple roles (graduate college staff, librarians, bindery, repository managers, etc) and some institutions have up to 150 Custom Actions.   In Vireo 3 they display in the order in which they were placed in Settings, but in Vireo 4 they currently do not.

**Comment by cstarcher** [comment]
The order is now updating on the student view, but the order is reversed from the Custom actions checklist in the admin view.
