### ISSUE TITLE
BUG - Student name is no longer appearing in the "Action By" column of the Action Log.

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1430]
![image](https://user-images.githubusercontent.com/35782552/76033017-c51ef300-5f00-11ea-9c1f-55178d46cdf4.png)

**Comment by mtpatterson** [comment]
Is this still a problem? I'm unable to reproduce this issue.

**Comment by StephanieVUGSC** [comment]
Just tested in https://test-etd.tdl.org/  and it seems to be fine there.  No longer a problem.  Thank you.
