### ISSUE TITLE
Add documentation to GitHub for migration of data from Vireo 3 to Vireo 4

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#1432]

**Comment by smutniak** [comment]
Added to wiki
https://github.com/TexasDigitalLibrary/Vireo/wiki/4.0.0-Migration-From-Vireo3-For-TDL-Hosted-ETDs

**Comment by smutniak** [comment]
Also added https://github.com/TexasDigitalLibrary/MigrateVireo3ToVireo4
