### ISSUE TITLE
SMTP configuration throwing errors

### ISSUE THREAD

**Issue by mobleyt** [TexasDigitalLibrary/Vireo#1433]
I am trying to stand up a new instance of Vireo 4 to work around our on-campus only Vireo instance in our current all-remote situation. It was overdue anyway.

Anyway, everything builds successfully and loads to index, but my SMTP configuration for our campus relay is failing in a few different ways. The server is a campus-only relay that doesn't require credentials. 

When I don't include credentials and leave username and password commented:

 `org.springframework.mail.MailAuthenticationException: Authentication failed; nested exception is javax.mail.AuthenticationFailedException: No authentication mechanisms supported by both server and client`

If I uncomment the username and password fields and leave them empty, I get a password missing error:

`Authentication failed; nested exception is javax.mail.AuthenticationFailedException: failed to connect, no password specified?`

If I uncomment username and password and use my credentials, the app never boots up at all.

Any ideas? Thanks!

**Comment by mobleyt** [comment]
This was seemingly resolved by removing the following lines from 


`emailService.setUsername(getConfigValue(ConfigurationName.APPLICATION_MAIL_USER, (String) username));`

and

`emailService.setPassword(getConfigValue(ConfigurationName.APPLICATION_MAIL_PASSWORD, (String) password));`

from /src/main/java/org/tdl/vireo/config/AppEmailConfig.java

**Comment by ublrama** [comment]
@mobleyt  You can achieve this by commenting "username" and "password"  in the application.yaml under email

![image](https://user-images.githubusercontent.com/50174699/82875034-24583680-9f37-11ea-9b29-5e09e837e810.png)

**Comment by cstarcher** [comment]
@mobleyt 

Are you still experiencing this issue?
