### ISSUE TITLE
Deposit Submission to deposit location causes error Hashmap to File cast issue

### ISSUE THREAD

**Issue by ublrama** [TexasDigitalLibrary/Vireo#1440]
Dear TDL,

When publishing a submission to a deposit location , the following error occurs at https://github.com/TexasDigitalLibrary/Vireo/blob/1d0e314fa44872463c65eaa653396d217bdf7a5f/src/main/java/org/tdl/vireo/model/depositor/SWORDv1Depositor.java#L122

`java.lang.ClassCastException: java.util.HashMap cannot be cast to java.io.File
	at org.tdl.vireo.model.depositor.SWORDv1Depositor.deposit(SWORDv1Depositor.java:191) ~[classes/:na]
	at org.tdl.vireo.controller.SubmissionController.publish(SubmissionController.java:425) ~[classes/:na]`

When doing the export the file is not a file, but a hashmap. We want to do a DSpaceMets export to our SWORD deposit location. This is unfortunately no possible due to this issue

**Comment by smutniak** [comment]
Vireo4 now gets past this original error on line 122, but in testing I did I did not get a response from the repository to which I tried to send a METS file.  The Deposit Location was set up and tested with no problem and a list of collections were returned.  I now get a 'ERROR: (409) Sword server responed with a non success HTTP status code: 401' as thrown in line 157. (note typo for 'responed')

I'm not sure yet if it is a dspace (training-ir.etd.org) or vireo4 problem.  What did you use for a dspace repo to test against?

**Comment by ublrama** [comment]
We created our own SWORD repository. Just like you, we managed to receive the collections with no problems. But when trying to deposit we get the HTTP status code 401, Unauthorised.

I changed the code to solve the original error on line 22 by adding a function that creates the DSpaceMets.zip  see here:
`  private String  createZipFile( DepositLocation depLocation,ExportPackage exportPackage) throws IOException {

        FileOutputStream fos = new FileOutputStream("DSpaceMets.zip");
        BufferedOutputStream bos = new BufferedOutputStream(fos);

        assets = new AssetService();

        try {
            ZipOutputStream zos = new ZipOutputStream(bos);


                String submissionName = "submission_" + exportPackage.getSubmission().getId() + "/";
                StringBuilder contentsText = new StringBuilder();
                if (exportPackage.isMap()) {
                    for (Map.Entry<String, File> fileEntry : ((Map<String, File>) exportPackage.getPayload()).entrySet()) {
                        if (depLocation.getPackager().getName().equals("MarcXML21")) {
                            zos.putNextEntry(new ZipEntry("MarcXML21/" + fileEntry.getKey()));
                        } else {
                            zos.putNextEntry(new ZipEntry(fileEntry.getKey()));
                        }
                        contentsText.append("MD " + fileEntry.getKey() + "\n");
                        zos.write(Files.readAllBytes(fileEntry.getValue().toPath()));
                        zos.closeEntry();
                    }
                }
                // LICENSES
                for (FieldValue ldfv : exportPackage.getSubmission().getLicenseDocumentFieldValues()) {
                    if(ldfv.getValue() != null){
                        logger.debug("LICENSES Doc:"+ldfv.getValue());
                        Path path = assets.getAssetsAbsolutePath(ldfv.getValue());
                        logger.debug("LICENSES Doc:"+ldfv.getValue().toString());
                        byte[] fileBytes = Files.readAllBytes(path);
                        zos.putNextEntry(new ZipEntry(submissionName + ldfv.getFileName()));
                        contentsText.append(ldfv.getFileName() + " bundle:LICENSE\n");
                        zos.write(fileBytes);
                        zos.closeEntry();
                    }

                }

                // PRIMARY_DOC
                FieldValue primaryDoc = exportPackage.getSubmission().getPrimaryDocumentFieldValue();

                Path path = assets.getAssetsAbsolutePath(primaryDoc.getValue());
                byte[] fileBytes = Files.readAllBytes(path);
                zos.putNextEntry(new ZipEntry(submissionName + primaryDoc.getFileName()));
                contentsText.append(primaryDoc.getFileName() + "  bundle:CONTENT  primary:true\n");
                zos.write(fileBytes);
                zos.closeEntry();

            zos.close();



        } catch (Exception e) {
            logger.info("Error With Export",e);
            fos.close();
        }

            return  depLocation.getPackager().getName() + "." + depLocation.getPackager().getFileExtension();
    }`

And update the the "deposit" function, see here:

`public String deposit(DepositLocation depLocation, ExportPackage exportPackage)  {

        try {
            URL repositoryURL = new URL(depLocation.getRepository());

            FileHelperUtility fileHelperUtility = new FileHelperUtility();

            // Building the client
            Client client = new Client();

            // get the timeout from the location, or default it to the default
            client.setSocketTimeout(depLocation.getTimeout() == null ? DepositLocation.DEFAULT_TIMEOUT : (depLocation.getTimeout() * 1000));
            client.setServer(repositoryURL.getHost(), repositoryURL.getPort());
            client.setUserAgent(USER_AGENT);

            // If the credentials include a username and password, set those on the client.
            if (depLocation.getUsername() != null && depLocation.getPassword() != null) {
                setAuthentication(client, depLocation);
            }

            PostMessage message = new PostMessage();
            try{

                String fos =  createZipFile(depLocation,exportPackage);
                File exportFile = new File(fos);

                //File exportFile = (File) exportPackage.getPayload();
                String exportMimeType = fileHelperUtility.getMimeType(exportFile);

                message.setFilepath(exportFile.getAbsolutePath());
                message.setDestination(depLocation.getCollection());
                message.setFiletype(exportMimeType);
                message.setUseMD5(false);
                message.setVerbose(false);
                message.setNoOp(true);
                message.setFormatNamespace(exportPackage.getFormat());
                message.setSlug("");
                message.setChecksumError(false);
                message.setUserAgent(USER_AGENT);

                if (depLocation.getOnBehalfOf() != null) {
                    message.setOnBehalfOf(depLocation.getOnBehalfOf());
                }
            }catch (IOException e){
                logger.info("Error With Export",e);
            }


            //DepositResponse response = postFileTest(message,depLocation);
            DepositResponse response = client.postFile(message);
            if (response.getHttpResponse() < 200 || response.getHttpResponse() > 204) {
                throw new SwordDepositException("Sword server responed with a non success HTTP status code: " + response.getHttpResponse());
            }

            try {
                URI sword = new URI(depLocation.getRepository());
                URI handle = new URI(response.getEntry().getId());

                String depositURL = sword.getScheme() + "://" + sword.getHost();
                if (sword.getPort() != -1) {
                    depositURL += ":" + sword.getPort();
                }
                depositURL += "/handle" + handle.getPath();

                return new URI(depositURL).toString();
            } catch (URISyntaxException e) {
                throw new SwordDepositException("Unable to publish to " + depLocation.getRepository(), e);
            }

        } catch (MalformedURLException | SWORDClientException e) {
            logger.debug(e.getMessage(), e);
            throw new SwordDepositException(e.getMessage(), e);
        }
    }`

I think this is a Vireo issue. I have tested our SWORD repository with a different client and I managed to deposit the Mets files. Only in Vireo do i receive the 401 Unauthorised HTTP status code

**Comment by jsavell** [comment]
@smutniak 

I tested against A&M Libraries' dev DSpace swordv1 webapp.

My Vireo instance received a 201 ok response from DSpace, and the item was visible in the repository.

**Comment by jsavell** [comment]
@ublrama 

You shouldn't need to add the additional deposit code. When Vireo is publishing with a manifest, it goes through a different pipeline that builds the zip file here:
https://github.com/TexasDigitalLibrary/Vireo/blob/master/src/main/java/org/tdl/vireo/model/packager/DSpaceMetsPackager.java#L40

The problem was that that pipeline was no longer being activated due to an earlier refactor that caused the wrong method to be fired.

I'm not experiencing the 401 that you and @smutniak are. But I will revisit this issue to see if I can recreate it.

My initial thought is that there could be a redirect happening that's causing the credentials to be dropped from the request.

**Comment by jsavell** [comment]
@smutniak @ublrama 

Are either/both of you using onBehalfOf for the deposit?

I haven't tried to deposit with that.

**Comment by ublrama** [comment]
@jsavell No I am not using "onBehalfOf". I tested the updated code and I was able to make a deposit to our repository! Thank you very much!
