### ISSUE TITLE
Cannot delete deposit location after failed deposit

### ISSUE THREAD

**Issue by ublrama** [TexasDigitalLibrary/Vireo#1467]
Hi,

When a deposit has failed with a submission, the deposit location can no longer be deleted. It seems that the reasons for this, is that the deposit location is still connected to the submission and therefor cannot be deleted.

![image](https://user-images.githubusercontent.com/50174699/83240686-09393100-a19a-11ea-9610-bea26ab0e99e.png)

![image](https://user-images.githubusercontent.com/50174699/83240704-10603f00-a19a-11ea-8e48-7371ad21ea12.png)

**Comment by jlong2git** [comment]
I also cannot delete deposit location. Maybe a JS issue
JS console

bundle.js:1 TypeError: Cannot read property 'status' of undefined
    at bundle.js:1
    at bundle.js:1
    at m.$digest (bundle.js:1)
    at m.$apply (bundle.js:1)
    at bundle.js:1
    at w (bundle.js:1)
    at XMLHttpRequest.E.onload (bundle.js:1) "Possibly unhandled rejection: {}"
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
g @ bundle.js:1
$digest @ bundle.js:1
$apply @ bundle.js:1
(anonymous) @ bundle.js:1
w @ bundle.js:1
E.onload @ bundle.js:1
load (async)
(anonymous) @ bundle.js:1
s @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
$digest @ bundle.js:1
$apply @ bundle.js:1
(anonymous) @ bundle.js:1
w @ bundle.js:1
E.onload @ bundle.js:1
load (async)
(anonymous) @ bundle.js:1
s @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
$digest @ bundle.js:1
$apply @ bundle.js:1
(anonymous) @ bundle.js:1
w @ bundle.js:1
E.onload @ bundle.js:1
load (async)
(anonymous) @ bundle.js:1
s @ bundle.js:1
(anonymous) @ bundle.js:1
(anonymous) @ bundle.js:1
$digest @ bundle.js:1
$apply @ bundle.js:1
(anonymous) @ bundle.js:1
dispatch @ bundle.js:1
y.handle @ bundle.js:1
