### ISSUE TITLE
DSpaceMets BatchExport missing mets.xml in zip file

### ISSUE THREAD

**Issue by ublrama** [TexasDigitalLibrary/Vireo#1485]
When doing a batch export with "DSpaceMETS" as selected format, the manifest file ,mets.xml, is missing in the zip file. While when you check the file in the payload of the export package `exportPackage.getPayload().toString()` , which prints out the path to the zip file, you will find the mets.xml file within the zip. 

But when the batch export is performed the mets.xml file is missing.

**Comment by smutniak** [comment]
related to #1468
