### ISSUE TITLE
SubmissionEmailService not able to get email sender address from EmailSender

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1494]
SubmissionEmailService.java does not correctly get the values expressed in managed_configuration name = email_from via WeaverEmailService at lines 112, 163, and 217.  It should also set smm.setReplyTo() the value at name='email_reply_to'  This error was encountered in the 2 production instances of vireo4 for utswmed and shsu.

**Comment by kaladay** [comment]
Issue #1274 brings some insight and solving this might solve that (or vice-versa) in regards to the email.from not appearing as it should.
