### ISSUE TITLE
Look and Feel setting not displaying content for heading choices

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1520]
![LookAndFeelHeadingError](https://user-images.githubusercontent.com/1197715/106062571-92ec2600-60bc-11eb-8acc-3d637a96b5b5.jpg)

**Comment by ublrama** [comment]
@smutniak  Which version of TinyMCE is set in the package.json?

I had to add  `ícons/**/*'` in Grunt.js at line 211

**Comment by cstarcher** [comment]
@smutniak I cannot reproduce this with a local spring-boot deployment. Can you give more context?

**Comment by cstarcher** [comment]
Cannot reproduce. Possibly resolved by upgrade to TinyMCE.
