### ISSUE TITLE
Who Has Access in Settings is not populated

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1522]
Settings>Application> Who Has Access > Add Member    button produces error

**Comment by cstarcher** [comment]
Further explanation by user:

I should be able to see who has access in the Settings area (Application Settings à Who Has Access).  I’ve attached a couple of screenshots, which clearly shows nothing in the list.
 
I believe – based on Vireo 3 – I should be able to see myself as anyone else who is an Admin or Manager.  And when I click on the “Add Member” button, I should also be able to see anyone with an account and set admin privileges.
 
As Frank mentioned, I can see a list of all users in the Manage Users drop-down and be able to promote/demote users to admin/manager roles from there.  But the Who Has Access view should show only the people who have the roles already assigned (without having to go through the full list).

![Screenshot 2020-12-09 14 17 45](https://user-images.githubusercontent.com/5767401/119224989-cb2dcf00-bac6-11eb-8218-aa22efc4554e.png)
![Screenshot 2020-12-09 14 18 45](https://user-images.githubusercontent.com/5767401/119224990-cbc66580-bac6-11eb-8c59-95001e7e7b39.png)
