### ISSUE TITLE
Alternate committee chair and member titles

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1526]
Out of the box the SYSTEM_Organization_Definition describes 2 classes of committee members: Committee Chair and Non-Chairing Committee Members.

In Vireo4 each term maps directly to a distinct dublin core value.  These are stored in the field_predicate table as attribute 'value' and used in abstract_field_profile.

Variances in Chair and Member names

Chair				dc.contributor.advisor		37
Member				dc.contributor.committeeMember	38

When those names get stored in V4.field_value they need to be associated with a V4.field_predicate

VIREO3 CUSTOMIZATIONS

Most vireo3 sites customized the terms they use for their committees. Below is a sampling of vireo3 committee roles as shown by "SELECT DISTINCT (roles) FROM committee_member_roles;"

Some options found in the various TDL vireo3 sites are:
 Chair
 Co-Chair
 Outside Chair
 External Chair
 Examining Committee Chair
 Committee Member
 Supervisor
 Co-Supervisor
 Reader
 Advisor
 Thesis Co-Director
 Dissertation Co-Director
 Thesis Director
 Dissertation Director
 Department Chair
 Associate Dean of the Graduate School 
 External Committee Member
 Department Head

EXPORTS

These dublin core values are used for DSpace and ProQuest exports.

DSpace exports (per templates found at src/main/resources/formats/) allow multiple 'advisor' dcvalue elements

        <dcvalue element="contributor" qualifier="advisor" th:text="${CCFV.getValue()}"></dcvalue>

and multiple 'committeeMember' dcvalue elements

        <dcvalue element="contributor" qualifier="committeeMember" th:text="${CMFV.getValue()}"></dcvalue>

Similarly ProQuest exports (proquest_umi.xml) allow something similar

        <DISS_name th:with="name=${committeeChairFieldValue.getValue()}">
            <DISS_surname th:text="${SUBMISSION_HELPER.getLastName(name)}"></DISS_surname>
            <DISS_fname th:text="${SUBMISSION_HELPER.getFirstName(name)}"></DISS_fname>
            <DISS_middle th:text="${SUBMISSION_HELPER.getMiddleName(name)}"></DISS_middle>
        </DISS_name>

        <DISS_name th:with="name=${committeeMemberFieldValue.getValue()}">
            <DISS_surname th:text="${SUBMISSION_HELPER.getLastName(name)}"></DISS_surname>
            <DISS_fname th:text="${SUBMISSION_HELPER.getFirstName(name)}"></DISS_fname>
            <DISS_middle th:text="${SUBMISSION_HELPER.getMiddleName(name)}"></DISS_middle>
        </DISS_name>

These values are returned by getCommitteeChairFieldValues and getCommitteeMemberFieldValues in vireo/utility/SubmissionHelperUtility.java and us
ed by vireo/model/formatter/ProQuestUmiFormatter.java and vireo/model/formatter/DSpaceSimpleFormatter.java

FIX?

One possiblity is to map these values to custom 'dublin core' values added to field_predicate, such as:

UTDallas:
	Co-Chair			dc.contributor.advisor.cochair
	Outside Chair			dc.contributor.advisor.outside
	External Chair			dc.contributor.advisor.external
	Examining Committee Chair	dc.contributor.advisor.examining
UTexas:
	Committee Member		dc.contributor.committeeMember
	Supervisor			dc.contributor.supervisor
	Co-Supervisor			dc.contributor.cosupervisor
	Reader				dc.contributor.reader

Then have getCommitteeChairFieldValues render any values found in cochair, supervisor, and cosupervisor (in addition to the current choices) and getCommitteMemberFieldValues render any values for the remaining other field_predicate values.  Any suggestions?

**Comment by smutniak** [comment]
There is some code in branch 4.1.1_addContributorVariants_1526 which needs to be updated and tested against the 4.1.2 branch

**Comment by smutniak** [comment]
This also relies on changes to SYSTEM_Organization_Definition.json generated from vireo3 data.

**Comment by jcreel** [comment]
Provide a review of Frank's work to vet it.
