### ISSUE TITLE
Allow free text entry for advisor or commitee member name and email (rather than drop down only) for submission entry

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1527]
Listed here for future discussion and possible change per TDL client site request

**Comment by cstarcher** [comment]
If I understand the issue correctly, this is already a feature. This can be achieved by editing the field profile in the organization workflow and changing the Input Type from INPUT_CONTACT_SELECT to INPUT_CONTACT.

<img width="1218" alt="Screen Shot 2022-03-23 at 3 03 36 PM" src="https://user-images.githubusercontent.com/5767401/159815981-e8e5719b-2ee1-4921-883b-cf5fd64dbe87.png">
