### ISSUE TITLE
Logout should return the user to the main page instead of an error/401 page with the 'Unauthorized' message

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1536]

**Comment by cstarcher** [comment]
When logging out while on the home page, the redirect is working.

When logging out from any other page, you are redirected to the home page and then to the 401 page.

**Comment by kaladay** [comment]
After the weaver upgrade, I am not ending up on an error page as described above.

Can I get a re-confirmation @smutniak or @cstarcher once 4.1.4 is released or if someone tests on the `4.1.3_spring2023_staging` branch or later.

**Comment by cstarcher** [comment]
Tested and confirmed resolved
