### ISSUE TITLE
Be able to reset an input select field to null after making a choice

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1567]
A vireo4 admin requested that, once a user has made a choice in an INPUT_SELECT or similar field, the user can then null it out.  e.g. A student chooses a Co-Chair accidentally and then wants to set the field back to empty (when 'required = no') the student should be able to do so.  It is not possible now.

**Comment by cstarcher** [comment]
Provide option with no value in drop down list.
