### ISSUE TITLE
allow an administrator to upload a primary document on a student's behalf 

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1568]
and have the name of the document reflect the students name and not that of the administrator

**Comment by jcreel** [comment]
Under "ALL FILES", 
- The name column should reflect the uploader (not the student, if it was done on their behalf by an admin).  
- The primary document rename should reflect the student's name (not the admin, if it was done on behalf of the student).

**Comment by cstarcher** [comment]
![Image](https://user-images.githubusercontent.com/5767401/224160961-e854d03e-3d81-4be2-b0f1-a5fe2d22e932.png)

**Comment by cstarcher** [comment]
https://github.com/TexasDigitalLibrary/Vireo/blob/main/src/main/java/org/tdl/vireo/controller/SubmissionController.java#L594
