### ISSUE TITLE
view must be reset before filter applied lest no items show in list

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1582]
The default sort order for the list view is “ID ascending”, and I have my default view set up to show 100 rows per page. I will periodically move to the end of the list (i.e., last page) to see the latest submissions. (See 1st screenshot for an example.)

If I then apply a filter, the display tells me how many records are in the filter (e.g., 22), but I don’t see the items in the list view, nor do I see any page numbers to pick from. (See 2nd screenshot for an example.)

To resolve the problem, I have to clear the filter, reset my view to be on the 1st page, and then reapply the filter to see the filtered items. And this would appear to be extra, unnecessary steps.
- Jon C.

**Comment by cstarcher** [comment]
Need clarification from Jon.

Which filter? Provide screenshots.

**Comment by smutniak** [comment]
![Image](https://user-images.githubusercontent.com/1197715/224395394-1e7739f7-87a6-4694-9e8e-8582825ee818.png)



![Image](https://user-images.githubusercontent.com/1197715/224395479-7d7e097d-b6af-4522-b976-d5f4cdf1fc8a.png)

**Comment by kaladay** [comment]
There are different things that can cause behavior like this.
1. Sometimes the network is slow and it is taking a while to render the table and you get this.
2. There is a problem where it simply doesn't render this as describe and shown here.

For the second case, I suggest checking to see if this is solved by PR:
- https://github.com/TexasDigitalLibrary/Vireo/pull/1631

That PR is intended to resolve this related issue:
- https://github.com/TexasDigitalLibrary/Vireo/issues/1584

**Comment by jcreel** [comment]
Clear pagination page index/number whenever a filter is applied.

**Comment by wwelling** [comment]
Shouldn't all viewers of this change apply the filter? I suggest the server-side broadcast the event and the client respond to the active filter change. Otherwise, refresh will be unpredictable by other subscribers to that public filter. The UI could have a refresh button somewhere to elevate the UI/UX experience.
