### ISSUE TITLE
alternate email sign in on shibboleth-enabled instances

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1585]
"The historical context would be to allow a former student (whose Shibboleth login credentials no longer exist) to login using an alternate email/password in case edits need to be made after they’ve gone. We had that issue come up several times during the Vireo 3 years, so it’s always possible it come up again."

While we do need a tech support sign in option I am also adding the above for discussion.

**Comment by jcreel** [comment]
This has not been supported in previous versions of Vireo.

**Comment by jcreel** [comment]
May relate to #1593

**Comment by smutniak** [comment]
My apologies for leading with the student sign in issue,  more importantly the tech support issue is what is core.  The interest is in getting a Vireo4 counterpart to vireo3's /PasswordAuthentication as in https://utexas-etd.tdl.org/login/PasswordAuthentication that can be used to sign in to TDL hosted sites that use shibboleth authentication.  Currently I need to make a local replica to a site on a local VM to debug issues rather than signing in via the UI to the site (e.g. I don't have TTU, WTAMU, UTD, etc shibboleth credentials) so I can see what the user/admin sees in the UI.

**Comment by cstarcher** [comment]
Password login not working behind proxy. Need to investigate how this works with DSpace.
