### ISSUE TITLE
Hide email/password login (optionally) when Shibboleth is configured (4.x Login)

### ISSUE THREAD

**Issue by nicksjunkyard** [TexasDigitalLibrary/Vireo#1593]
How do we go about disabling vireo based login or make Shibboleth login the default? It would be nice to get rid of the register menu item and will be confusing to have two login choices. Thank you!

**Comment by jcreel** [comment]
May relate to #1585

**Comment by cstarcher** [comment]
Need to update README with instructions for removing non-Shibboleth login.

**Comment by jcreel** [comment]
Add a configuration value (appConfig.js to avoid DB migration) to indicate if the "Login" link should go straight to Shibboleth or should bring up the modal.
