### ISSUE TITLE
keyword entry separated by semicolons create a single keyword

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1594]
separate entries of keywords via UI create separate field_value entries with the same field_predicate.  If the keywords are entered on one keyword entry line and separated by a semicolon, the whole keyword string is stored in a single field_value.  The keywords should have a consistent storage (and hence easy export) and not be stored differently for different entry methods.

**Comment by jcreel** [comment]
- [ ] Migrate legacy database values with semicolons to have separate field values
- [ ] Hover text "You can enter multiple keywords. Use semi-colons ( ; ) to separate the entries." is misleading in current UI.
Fix the text for now.  A more robust UI would be additional cards.

**Comment by cstarcher** [comment]
This issue was solved with the linked PR.
