### ISSUE TITLE
Security Alerts - Weaver Upgrade

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1598]
Review Dependabot security alerts

TinyMCE
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/12
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/6
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/5
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/4
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/2
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/1

Apache POI
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/11

Grunt
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/10
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/3
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/9

Karma
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/8
- [x] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/7

**Comment by jcreel** [comment]
For each issue found at https://github.com/TexasDigitalLibrary/Vireo/security/dependabot, either:
1. Document a justification to accept risk
2. Document a plan to remediate
3. Quickly fix :)

**Comment by cstarcher** [comment]
TinyMCE
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/12
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/6
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/5
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/4
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/2
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/1

Apache POI
- [ ] - [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/11

Grunt
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/10
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/3
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/9

Karma
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/8
- [ ] https://github.com/TexasDigitalLibrary/Vireo/security/dependabot/7

**Comment by kaladay** [comment]
For reference in case weaver is decided to be upgrading during this, there are these old weaver-upgrade issues:
- https://github.com/TexasDigitalLibrary/Vireo/issues/1565
- https://github.com/TexasDigitalLibrary/Vireo/issues/1558

It also appears that I have an old and probably incomplete branch regarding weaver upgrade here:
- https://github.com/TexasDigitalLibrary/Vireo/tree/1558-weaver_upgrade
