### ISSUE TITLE
Graduation dates sometimes stored improperly such that graduation date filters will not work properly

### ISSUE THREAD

**Issue by smutniak** [TexasDigitalLibrary/Vireo#1599]
These happened for submissions created after the migration so it must be something that happened in Vireo4.  The dates were off only by a time zone.  The date is stored as 2022-12-01T05:0:0.000Z or similar.  The dates in error were off by one timezone.  Presumably the timezone is based on when the graduation date was selected.  If a December graduation date is selected sometime during Daylight Savings Time (spring to fall) then the time recorded is actually 1 hour closer to GMT than it will be in December, but Dec 1 at midnight a timezone offset from GMT by 5 hours is Nov 30 11pm for a timezone offset from GMT by 6 hours.
(more rarely some dates were actually off by a day, e.g. 2022-12-02T05:0:0:0.000Z but I don't have a theory for that yet)

**Comment by kaladay** [comment]
For reference, the Field Predicate name for Graduation Date is `dc.date.issued`.

I see a difference between the CLI generated data and the manually created submissions for their values. They look like this:
```
  id  | definition | identifier |          value           | field_predicate_id 
------+------------+------------+--------------------------+--------------------
 7905 |            |            | 06/30/2019               |                 30
 7940 |            |            | 04/29/2018               |                 30
 7975 |            |            | 07/29/2017               |                 30
 8028 |            |            | 2023-08-03T05:00:00.000Z |                 30
 8046 |            |            | 2023-12-01T06:00:00.000Z |                 30
 8072 |            |            | 2023-05-01T05:00:00.000Z |                 30
```

It is clear that something is **improperly** putting a datetime rather than a date (aka date without time).

**Comment by kaladay** [comment]
When selecting the graduation date via the calendar in the UI I am seeing the request packet containing a payload with a value of something like this:
```
value: "2023-12-01T06:00:00.000Z"
```

This could be a problem with the UI introducing the values incorrectly.
I will investigate further.

**Comment by kaladay** [comment]
Upstream reference:
- https://github.com/smalot/bootstrap-datetimepicker/issues/587
