### ISSUE TITLE
Console error on organization settings view

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1614]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/8352733/226916370-6adc9b66-5188-496c-aab0-14a209fd19bf.png">

**Comment by wwelling** [comment]
Already resolved by commit https://github.com/TexasDigitalLibrary/Vireo/commit/888f688a3a6ea881f59d33545959251d8c4f4101

**Comment by cstarcher** [comment]
I cannot reproduce this exception.
