### ISSUE TITLE
Drop down select icon on submission not vertically aligned

### ISSUE THREAD

**Issue by ghost** [TexasDigitalLibrary/Vireo#1615]
On Edge

<img width="465" alt="image" src="https://user-images.githubusercontent.com/8352733/226917090-ce5b7901-5c9e-4014-8077-c0e10396503e.png">

**Comment by cstarcher** [comment]
Also, glyphicons are not horizontally centered as they are for other inputs.

**Comment by cstarcher** [comment]
Fixed in version 4.2.6.
