### ISSUE TITLE
Cannot delete file via web interface if file is missing on the disk.

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1632]
During testing, I uploaded a file.
Then I restarted the the system while preserving the DB tables and respective data but I cleared the local file cache.
This caused the situation where the file is referenced but cannot be found.

![Example of broken file showing NaN undefined](https://user-images.githubusercontent.com/35114839/227633908-e54ed32e-f83b-4a7a-8963-912d000e7302.png)

I figured I could just delete it.
It won't let me delete the file because the local file is not found.

```
ERROR: (500) vireo/target/classes/private/587811713/1679688528996-DANIELS-PRIMARY-2023.pdf 
```

This is a request to not error out on delete if the file is missing from the disk.
Just treat it as a warning and remove the reference from the DB.

This is observed on the Student Submission View but may very well be affecting all of the file removals on the system.

**Comment by wwelling** [comment]
@jcreel @cstarcher @kaladay I am able to reproduce. Now what should the application do when the file was removed?

**Comment by wwelling** [comment]
Getting this when running VSCode.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.0:resources (default-resources) on project vireo: copying C:\Users\william\Development\work\Vireo\node_modules\bootstrap-sass\assets\stylesheets\bootstrap\mixins\_size.scss to C:\Users\william\Development\work\Vireo\target\classes\stylesheets\bootstrap\mixins\_size.scss failed with FileSystemException: C:\Users\william\Development\work\Vireo\target\classes\stylesheets\bootstrap\mixins\_size.scss: The process cannot access the file because it is being used by another process.
```

**Comment by wwelling** [comment]
![Image](https://user-images.githubusercontent.com/8352733/229888565-ccb094e2-398e-4bb5-bb29-5832f6f19b45.png)

Reproducing labs issuee...

**Comment by wwelling** [comment]
![Image](https://user-images.githubusercontent.com/8352733/229891654-17c27080-e93f-4ddb-bc0d-497c3490cd71.png)

🤞

**Comment by wwelling** [comment]
@kaladay here is the work in progress [Cannot delete file via web interface if file is missing on the disk.#1632](https://github.com/TexasDigitalLibrary/Vireo/issues/1632). I am moving onto [Console error on organization settings view#1614](https://github.com/TexasDigitalLibrary/Vireo/issues/1614)
