### ISSUE TITLE
ERROR 500 JSON Serialization - duplicated inputs when cleared

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1635]
ERROR: (500) Could not write JSON: No serializer found for class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: edu.tamu.weaver.response.ApiResponse["payload"]->java.util.HashMap["Submission"]->org.tdl.vireo.model.Submission["organization"]->org.tdl.vireo.model.Organization_$$_jvst232_d["aggregateWorkflowSteps"]->org.hibernate.collection.internal.PersistentList[0]->org.tdl.vireo.model.WorkflowStep["aggregateFieldProfiles"]->org.hibernate.collection.internal.PersistentList[1]->org.tdl.vireo.model.FieldProfile["fieldPredicate"]->org.tdl.vireo.model.FieldPredicate_$$_jvst232_2d["handler"])

**Comment by cstarcher** [comment]
To reproduce, enter middle name then delete middle name.

**Comment by wwelling** [comment]
@cstarcher I will debug this.

**Comment by wwelling** [comment]
However, it appears there is a bug in when clearing out an input. After clearing the input and clicking away the empty input is duplicated.



![Image](https://user-images.githubusercontent.com/8352733/228077028-240f8378-79aa-40bf-9f55-5be1855dafc4.png)

![Image](https://user-images.githubusercontent.com/8352733/228077072-bf83a091-a090-4b94-acd0-a3714a61c653.png)
