### ISSUE TITLE
Retain focus on modal until closed

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1661]
Relevant Components:

- All Modals

Description
The login modal on the home page allows focus to continue onto the rest of the page.

This can cause confusion for non-sighted or low vision users because the screen reader will continue to announce the next focused element, and the user is likely unaware that there is a modal open at all.

Employing a keyboard trap while the modal is open, as well as manually setting focus to the modal on its appearance, will make the element more accessible as well as more usable in general.
Solution
Make sure the modal acts as can be reasonably expected by a user - specifically, focus should remain in the modal.

Relates to #1660

**Comment by kaladay** [comment]
This might be solvable using ARIA live regions to hint at what to focus on:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Region_role

**Comment by jcreel** [comment]
Deliverable for spike:  A technique to reliably maintain tab focus within a modal.  Tab order should cycle back to top of modal after hitting the last element.
