### ISSUE TITLE
Advisor E-mails are not being sent once properly setup.

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1666]
There are two issues observed that can be fixed in the same spot.

The Advisor e-mail is being handled via the `EmailRecipientContact`.

This [getEmails() function](https://github.com/TexasDigitalLibrary/Vireo/blob/2dd16920cba6e10f65c8f7c6a10e872a8c4c7909/src/main/java/org/tdl/vireo/model/EmailRecipientContact.java#L33) has these mistakes:
1. The advisor e-mail is the value of the field value and not a contact added on.
2. The query `submission.getFieldValuesByPredicate()` is not appearing to work.

This problem may exist in every class implementing `implements EmailRecipient`. I suggest reviewing and fixing each of those.

I suggest the following solution (and I can confirm it works):
1. Change the code to use the field values from the submission that is passed as an argument.
2. Filter the field predicate by ids based on the predicate attached to the email recipient model.
3. Add the advisor e-mail by value in addition to the contacts.

Example snippet that could be a fix:
```java
...
        for (FieldValue fv : submission.getFieldValues()) {

            if (fv.getFieldPredicate().getId() != fieldPredicate.getId()) continue;

            if (!emails.contains(fv.getValue())) {
                emails.add(fv.getValue());
            }

            for (String contact : fv.getContacts()) {
                if (!emails.contains(contact))
                    emails.add(contact);
...
```

**Comment by kaladay** [comment]
E-mails appear to be working now without any changes.

This may no longer be a problem.

**Comment by jcreel** [comment]
Remove Advisor from the dropdown for email recipient.  It means the same thing as Committee Chair and need not be there.

**Comment by kaladay** [comment]
The solution proposed here is an effective partial revert of:
- https://github.com/TexasDigitalLibrary/Vireo/pull/1349
- https://github.com/TexasDigitalLibrary/Vireo/issues/1329

And relates to these issues:
- https://github.com/TexasDigitalLibrary/Vireo/issues/1303
- https://github.com/TexasDigitalLibrary/Vireo/issues/1305
- https://github.com/TexasDigitalLibrary/Vireo/pull/1312
- https://github.com/TexasDigitalLibrary/Vireo/issues/1231
