### ISSUE TITLE
Using a Saved Filter can cause system to be unresponsive for long periods of time.

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1667]
### The Problem
After having customizing a view and thensaving the filters, I selected the saved filter.
After loading I may have refreshed the page.
The page just sat their looking broken.
Several long seconds later, the page suddenly worked.

### To Reproduce
1. Add some columns to the Customize View, such as Custom Actions and Notes.
2. Select Title, Customize Filter, and add Custom Actions and Notes as well.
3. Filter by a Title, such as "test" (Make sure "test" is set for Title on at least one Submission).
4. Select "Save current filter".
  1. Fill in the name, such as "Filter by Test Title".
  2. Select the Public checkbox of "I would like this filter to be available to all users.".
  3. Select the Columns checkbox of "I would like this filter to include visible columns.".
  4. Click Save.
5. Under the "Saved Filters", under "With Columns", Select the saved filter by the name you just created, such as "Filter by Test Title".
6. Seems to work, now refresh the page.
7. The problem is observed here to have a very slow load that does not seem to work. Observe the network log.

**Comment by cstarcher** [comment]
Decomposition and actionable cards for resolution.

**Comment by wwelling** [comment]
*then saving

Unable to reproduce.

@kaladay How many submissions did you have generated? Was expansive enabled for all of them?

**Comment by kaladay** [comment]
I had 111000 Submissions at the demo where this problem was clearly observed.
Expansive was enabled.

I filtered by "title" with a value of "test" and saved that filter.
Compare filtering by "title" without using the saved filter vs filtering by "title" via the saved filter. A huge difference.

It can also help to have multuple browsers/tabs open to refresh and see the problem get worse fast.

**Comment by wwelling** [comment]
What do you mean? `Select Title, Customize Filter, and add Custom Actions and Notes as well.`

**Comment by wwelling** [comment]
Do you mean add a title filter?

**Comment by wwelling** [comment]
>Filter by a Title, such as "test" (Make sure "test" is set for Title on at least one Submission).
generated data test is in all title. not relevant experiment to reproduce ... induced so far.

**Comment by wwelling** [comment]
>Select the Public checkbox of "I would like this filter to be available to all users.".
Select the Columns checkbox of "I would like this filter to include visible columns.".

select is the incorrect verb. it should be check the public and column checkbox

**Comment by wwelling** [comment]
>Under the "Saved Filters", under "With Columns", Select the saved filter by the name you just created, such as "Filter by Test Title".

Is this step necessary? Is it not already providing the results. Clicking `With Columns
 [Filter by Test Title](http://localhost:9000/#)` anyhow.

**Comment by wwelling** [comment]
Unable to reproduce with page 1000 while generating 100000 submissions using expansive.

**Comment by wwelling** [comment]
@kaladay could you update this issue with blocking requests you are experiencing? I have not been able to reproduce yet.

**Comment by kaladay** [comment]
The issue as described above reproduces the problem.

I have been able to confirm that the problem does happen on 4.1.3 so it is an existing bug rather than a recent regression.

**Comment by wwelling** [comment]
I will test again when more submissions are generated.

![Image](https://user-images.githubusercontent.com/8352733/234028183-5e9b9ebd-cfd1-4af2-913f-dc6c01e0af3f.png)

**Comment by wwelling** [comment]
It has been discovered that this performance issue can be toggled on and off by `Clear current filter` and select Saved filter with Columns.


![Image](https://user-images.githubusercontent.com/8352733/234290925-bbb88ff1-f732-4d6a-901e-22facea0548e.png)

Removing the filter from Now Filtering By does not improve the performance.



![Image](https://user-images.githubusercontent.com/8352733/234291566-c5b65321-8414-4e03-8702-07e7f424e460.png)

**Comment by wwelling** [comment]
```
http://localhost:9000/submission-list/remove-filter-criterion/Title
```

vs

```
http://localhost:9000/submission-list/clear-filter-criteria
```

**Comment by wwelling** [comment]
I have reduced the performance issue down to when the active filter includes visible columns. The same filter without columns performs ~2x faster than with columns.

**Comment by kaladay** [comment]
In case the weaver-ui-core change is lost in the "link" messages above, here is an explicit link to it:
- https://github.com/TAMULib/Weaver-UI-Core/pull/233
