### ISSUE TITLE
Make tooltips keyboard accessible

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1669]
Relevant Components

- [ ] Document Information
- [ ] File Upload
- [ ] Settings

Description
Everything on the page that is accessible via mouse needs to be accessible via keyboard as well. The tooltips next to the inputs which appear on hover do not appear in the tab order, and thus are inaccessible by keyboard. This creates a problem for users who navigate either mostly or solely by keyboard. 

Make sure everything that is available via mouse is also available via keyboard.
Current Code
```<span ng-mouseenter="function1()" ng-mouseleave="function2()"></span>```
Solution
Add a tabindex of 0 to the element. This allows the element to be focused by keyboard, using the “tab” key. Alternatively, if the page features an ordered tabindex cascade, fit it in where it makes sense.

onmouseenter and onmouseleave are device dependent events. They only fire from the mouse input. Whenever possible, use device independent events, such as onfocus and onblur. Onfocus and onblur fire when the element receives or loses focus, which can be caused by either the mouse or the keyboard.

Note: The above “recommended code” could cause issues if children are not cleared at the beginning of function1.
Recommended Code
```
<span tabindex="0" 
  ng-mouseenter="function1()" 
  ng-mouseleave="function2()" 
  onfocus="function1()" 
  onblur="function2()"></span>
```

**Comment by jcreel** [comment]
ARIA-A has live regions that may help.

**Comment by wwelling** [comment]
You 10:16 AM
pick one, the mouse or the keyboard
regression!
async save response is propagating to a mouse or keyboard event
is more accessible or less?
it moved onto the next field when saved
what is the desired behavior?
^^ need answers or porting to issue

**Comment by cstarcher** [comment]
Able to reproduce in 4.2.7. However, since the subsequent tab stroke after the save does move to the tooltip, I am closing this issue.
