### ISSUE TITLE
After deleting a file, the screen is not scrollable.

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1682]
This happens on the student submission view.

I have tested this across different browsers and found the problem to be consistent.

### Steps to reproduce:
1) Login and create a submission.
2) Upload a file to that submission.
3) Delete that file.
4) Attempt to scroll after the delete modal closes.

**Comment by wwelling** [comment]
@kaladay can we get this on labs? There are too many variables trying to reproduce your issues.

**Comment by kaladay** [comment]
There aren't many variables at all as far as I can tell.

Additional notes:
1. Just start from a fresh database.
2. Enable submissions, and keep it simple by enabling submissions for the institution.
3. Create a submission, don't bother with filling anything out.
4. Got to the file upload.
5. Perform the steps above.

This is very easy to reproduce.
