### ISSUE TITLE
Page reload required after deleting organization

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1684]
As you can see in the alert, I deleted Program2 from Department2.

<img width="1143" alt="Screenshot 2023-04-06 at 11 00 00 PM" src="https://user-images.githubusercontent.com/5767401/230538715-8748dd64-defd-47b3-bf13-a03372efd71c.png">

It required a page reload to remove Program2 from the triptych.

<img width="1150" alt="Screenshot 2023-04-06 at 11 00 24 PM" src="https://user-images.githubusercontent.com/5767401/230538734-11cf70a2-9c2f-4260-b2fe-d10b2b9e40b9.png">

**Comment by kaladay** [comment]
The issue #721 may or may not be related.

**Comment by cstarcher** [comment]
Closing as resolved as of version 4.2.7.
