### ISSUE TITLE
Adding custom actions to the submission List columns breaks sorting

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1689]
**Steps to reproduce**

as admin

1. Navigate to List view
2. Click Customize view
3. Drag `Custom Actions` from Disabled Columns to Displayed Columns
4. Save
5. Attempt to sort on any column

**Actual**

When adding `Custom Actions` to submission list columns, the sorting does not work.

**Expected**

When adding `Custom Actions` to submission list columns, the sorting does work.

**Comment by wwelling** [comment]
It may be that other columns break the sorting as well.

**Comment by cstarcher** [comment]
Unable to reproduce on 4.1.5_staging
