### ISSUE TITLE
Remove existing filters not actually removing persistence *unable to save with same name

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#1724]
There may be additional requirements needed to be gathered. Such as, what is the expected result of removing a public filter? how to handle duplicate names of public filters? and what feedback should be presented in the UI?

To reproduce

1. Log in as admin
2. Navigate to the list view
4. Customize filters adding Title *will appear in Further Filter By sidebar box
5. Filter title by text "test"
6. Save current filter with a specific *name*
7. Remove existing filter removing the filter with the specific *name* from step 6
8. Save current filter with same specific *name* from step 6 and 8

Expected to be able to recreate filter with specified *name*.

If while saving current filter the public checkbox is not checked the following error occurs.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/8352733/234111082-f364e302-0b86-4e53-a960-82e2a93e0830.png">

```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "uka8mgybhu9ik92wg8u3mrnytpl"
  Detail: Key (user_id, name)=(32, Test 2) already exists.
```

**Comment by jcreel** [comment]
Will be resolved in https://github.com/TexasDigitalLibrary/Vireo/issues/1738

**Comment by jcreel** [comment]
https://github.com/TexasDigitalLibrary/Vireo/issues/1738
