### ISSUE TITLE
With multiple screens for same user, admin list view doesn't refresh on second pages when first has filter applied.

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1759]
Take two webbrowser pages for the same user with both on the admin list view.
When one has a filter applied the other updates, showing the applied filter.
However, the other one does not refresh the table and the table is inconsistent with the filter applied.

This is easily reproducible by just using an exclusion filter (clicking the `x` next to a row).
Other filters, such as the "id" or the "title" filters, also reproduce the problem.

### To Reproduce
1. Open two browsers and navigate to the admin list view page.
2. For one of the rows, select the `x` link that performs an exclude filter for that row.
3. The exlude filter should appear on both screens.
4. The admin list view table only refreshes on the screen where you clicked the `x` link.

**Comment by cstarcher** [comment]
Unable to reproduce in version 4.2.7.
