### ISSUE TITLE
Date fields not displaying correctly on "Confirm and Submit" step

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1768]
When a date field is empty, it does not display correctly on the "Confirm and Submit" step in the submission workflow.

![Screenshot 2023-05-05 at 9 02 40 AM](https://user-images.githubusercontent.com/5767401/236480590-ede748f2-b11d-48b9-9ee3-fb6c562c89f9.png)

**Comment by jcreel** [comment]
Please provide steps to reproduce.

**Comment by cstarcher** [comment]
Confirmed no longer happening.
