### ISSUE TITLE
Console TypeError and RangeError on "Confirm and Submit" step

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#1769]
The console shows TypeError and RangeError for each empty field on the "Confirm and Submit" step in the submission workflow.

![Screenshot 2023-05-05 at 9 11 59 AM](https://user-images.githubusercontent.com/5767401/236482929-831da25e-7ad4-4bd5-b8c6-f78e1cc4455b.png)

**Comment by jcreel** [comment]
Please provide steps to reproduce.

**Comment by cstarcher** [comment]
Confirmed no longer happening.
