### ISSUE TITLE
Do not create multiple duplicate columns in "Now Filtering By".

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1788]
This has been created from the spike investigation of #1781.

This is intended to address a specific problem identified by the referenced issue.

### Current behavior
When multiple users save a public filter with the same name, the filter appears multiple times under "Now filtering By" when one of the saved filters is applied.

### Expected behavior
Only the selected filter should show under "Now filtering By"

### What to Fix
The problem to fix here is the case where there are multiple duplicate columns.
This issue is not about addressing the underlying cause that results in multiple similarly named data.

Instead, this is for solving the situation in which if for any reason multiple columns would be displayed only a single column is displayed. Multiple filters for the identical column can be different and if they are they should be combined into the same filter.

**Comment by jcreel** [comment]
We hope this won't happen anymore with recent fixes to keep the filters in the database correct.

**Comment by cstarcher** [comment]
The system no longer allows multiple public filters with the same name.
