### ISSUE TITLE
SPIKE: Active Filter List in Admin Submission View is not always refreshing.

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#1795]
When loading an active filter, the filter does not refresh.

Investigation has revealed that for the active filter, the UI is listening on the channel for the old filter ID. If the active filter changes in any way then a new broadcast is sent out using the new filter ID rather than the old filter ID. As a result, the UI does not refresh the Active Filter List (Now Filtering By).

Code prior to 4.2.1 is performing a `clone()` and broadcasting using the old filter ID with the cloned filter as the value associated with it.
The newer code is using the new filter ID when broadcasting rather than the old filter ID.
This is not a regression but is instead exposing an existing bug.

This problem likely exists in multiple places where the active filter is changed in some way and a broadcast is sent out to the channel.

The old behavior:
- https://github.com/TexasDigitalLibrary/Vireo/blob/8ff079ba606173e16782f418444ab4d65a497160/src/main/java/org/tdl/vireo/controller/SubmissionListController.java#L162

The updated behavior:
- https://github.com/TexasDigitalLibrary/Vireo/blob/5098dae99c65f84a955e6f958d55d8a4bf60fcfa/src/main/java/org/tdl/vireo/controller/SubmissionListController.java#L164

Example change in the new code that helps reveal the problem described above:
```java
    @RequestMapping(value = "/set-active-filter", method = POST)
    public ApiResponse setActiveFilter(@WeaverUser User user, @RequestBody NamedSearchFilterGroup namedSearchFilterGroup) {

        Optional<NamedSearchFilterGroup> desiredFilter = namedSearchFilterGroupRepo.findById(namedSearchFilterGroup.getId());

        if (desiredFilter.isEmpty()) {
            return new ApiResponse(ERROR, "Failed to find filter with ID " + namedSearchFilterGroup.getId() + ".");
        }

        NamedSearchFilterGroup activeFilter = user.getActiveFilter();

        user.setActiveFilter(desiredFilter.get());

        user = userRepo.update(user);

        if (activeFilter != null) {
            simpMessagingTemplate.convertAndSend("/channel/active-filters/" + activeFilter.getId(), new ApiResponse(SUCCESS, user.getActiveFilter()));
        }

        simpMessagingTemplate.convertAndSend("/channel/active-filters/" + user.getActiveFilter().getId(), new ApiResponse(SUCCESS, user.getActiveFilter()));

        return new ApiResponse(SUCCESS);
    }
```

Notice how this example is sending both the old and the new.

What likely needs to happen is to not change the back end but instead change the front end.
The UI should probably listen on the user model and watch for changes.
As an example, if there is a new listener channel, such as `/channel/user/[user id]/active-filter`, then this could be listened on.

An alternative solution could be to use the user ID rather than the filter ID in the channel.
The active filters are each associated with a single user and so using such a channel the user ID can consistently designate that the active filter for some user has been changed.

This would look like:
```java
simpMessagingTemplate.convertAndSend("/channel/active-filters/" + user.getId(), new ApiResponse(SUCCESS, user.getActiveFilter()));
```

Also note that the java code snippet far above is an example only.
Using it reveals that the first message is received but then follow up messages fail.
There is likely more to the problem than what is recorded here thus far.

**Comment by jcreel** [comment]
Sized as completing this investigation.

**Comment by kaladay** [comment]
The following are statements copied from my Slack conversation on May 31, 2023:
> From the backend point of view, my suggestion there looks fine.
But now that I am looking into the frontend, I am seeing problems with the approach that I do not think will be great, such as:
- The user model being received does not contain everything (it is missing the activeFilter).
- The listeners is some built in weaver-ui-core design and changing this would be more work,
- The apiMapping is mapping active filter in the NamedSearchFilterGroup mapping, which is confusing and messy (I don't want to make this even more confusing).
I am now starting to favor the use of the wrong/old filter ID when sending the channel broadcast approach (which is what the older code did).

Followed by:
> I experimented with using the old filter ID and there are still weird problems.
It updates the first time but not thereafter.
This issue clearly needs some more thorough investigation.
