### ISSUE TITLE
Errors uploading items

### ISSUE THREAD

**Issue by nicksjunkyard** [TexasDigitalLibrary/Vireo#1852]
I have built Vireo 4.2.3 and have noticed a few errors in the log. Users can successfully login using shibboleth but the log is showing
org.tdl.vireo.controller.UserController  : No User With Username anonymousUser

When I try to upload logos the system says 
ERROR: (413) File size limit exceeded

It looks like the new version of vireo uses application.yml instead of .yaml and I have it stored in /opt/vireo/config

Please let me know how to troubleshoot these issues.

**Comment by kaladay** [comment]
The https://github.com/TexasDigitalLibrary/Vireo/blob/f80a44528d2148e385feb825540a575cf0a7e081/src/main/resources/application.yml#L28 
has the following:
```
      maxFileSize: 20MB
      # Total request size for a multipart/form-data
      maxRequestSize: 20MB
```

That default is usually plenty.
There may be other problems with proxies, nginx, apache, Tomcat, etc... that is providing Vireo.

For setups with an Nginx proxy, the following documentation may be of assistance (take note of the comments regarding `proxy-body-size` in addition to `client_max_body_size`):
- https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

**Comment by nicksjunkyard** [comment]
Thank you! Setting the maxFileSize and giving tomcat right to the temp folder fixed the issue.
