### ISSUE TITLE
Set password for local user

### ISSUE THREAD

**Issue by nicksjunkyard** [TexasDigitalLibrary/Vireo#1863]
How do I create a local user with a password? Clicking on the registration link in email allows me to set name and password but it errors out. The error is blank. I wonder if I need to run mvn and create a user that way.

**Comment by cstarcher** [comment]
Your server must be setup to send mail. Did you set the email settings in the [application.yml](https://github.com/TexasDigitalLibrary/Vireo/blob/c0ee29f42df1b2c0aad1e88058b51ddbcbf34b87/src/main/resources/application.yml#L148)?
