### ISSUE TITLE
Excel export error for repeatable fields

### ISSUE THREAD

**Issue by labuchholz** [TexasDigitalLibrary/Vireo#1880]
[*] Bug Report

Current Behavior:
For excel exports, only the first value of a repeatable field is exported. For example, "adviser" is a repeatable field for us, and submitters can (correctly) add two advisers. Reviewers (correctly) see both advisers in both List and View. But Excel (incorrectly) exports only the first.

Desired Behavior:
Export all values present for repeatable fields, separated by a standard delimiter (semi colon or pipe or such).

Relevant Information:
I have only tested this on our adviser field, which has type INPUT_CONTACT_SELECT and is connected to a CV.

**Comment by cstarcher** [comment]
I can confirm that the excel export is only exporting the first value for repeatable field values. I tested this with both default fields profiles and new field profiles marked as `Repeatable`.
