### ISSUE TITLE
Signature page upload fails

### ISSUE THREAD

**Issue by nicksjunkyard** [TexasDigitalLibrary/Vireo#1919]
My library is using vireo 4.2.6
Students are having difficulty uploading signature pages from docusign. The upload gets to 100% but  the arrows continue to spin. I have had success exporting the pdf to word. I can send a copy of a failed pdf but prefer not to upload it in the forum.

**Comment by cstarcher** [comment]
@nicksjunkyard Is this issue still occurring? If so, would you mind sending me a copy of a document that failed to upload?

**Comment by nicksjunkyard** [comment]
Please close this ticket. We just upgraded to 4.2.9 and noticed it might
fix some file uploads. Thank you!
