### ISSUE TITLE
Upgrade Documentation from Vireo 2.0.4 

### ISSUE THREAD

**Issue by misilot** [TexasDigitalLibrary/Vireo#52]
Hi,

I looked around and could not find any upgrade information.

Do you have any recommendations in regards to this?

Thank you

**Comment by misilot** [comment]
Nevermind found it. Was looking on vireoetd.org

https://github.com/TexasDigitalLibrary/Vireo/wiki/Upgrade#upgrade-from-20x-to-301

**Comment by gadkrumholz** [comment]
Just an FYI... we're at 3.0.2 now. Documentation is still the same though.

**Comment by misilot** [comment]
Thank you @gadkrumholz Looking to upgrade once the semester is over.
