### ISSUE TITLE
Test Conflicts

### ISSUE THREAD

**Issue by jmicah** [TexasDigitalLibrary/Vireo#53]
Affects v3.0.3

If you run the org/tdl/vireo/services/SystemDataLoaderTest prior to the controllers/FilterTabTest, it will cause the FilterTabTest to fail.
![screen shot 2015-07-06 at 8 45 19 am](https://cloud.githubusercontent.com/assets/1618538/8523528/865e9a88-23bb-11e5-9af6-328bd3ea1d4d.png)

**Comment by gadkrumholz** [comment]
Some of the tests don't leave the H2 DB in a "known" state even though they think they do... and running tests "out of order" (meaning, from top to bottom) can cause these kinds of errors.

Stopping and restarting the "play test" command is the workaround for now.
