### ISSUE TITLE
Version 3.0.4 - Compilation error(s) related to JDOM (?)

### ISSUE THREAD

**Issue by dheles** [TexasDigitalLibrary/Vireo#56]
While attempting to upgrade Vireo 2.0.4 to 3.0.4 (as per https://github.com/TexasDigitalLibrary/Vireo/wiki/Upgrade#upgrade-from-20x-to-303), I am receiving the following error on initial attempt to access the application:

    The file /app/org/tdl/vireo/services/Utilities.java could not be compiled. 
    Error raised is : org.jdom.Document cannot be resolved

If I stuff jdom-1.1.3.jar into lib, everything seems to work ok. (JDOM 1.1.3 is "the latest stable and supported version of JDOM from the 1.x branch." JDOM 2 doesn’t work).

However, as an attempt at a proper fix, I added JDOM as a dependency (in conf/dependencies.yml):

     - org.jdom -> jdom 1.1.3

But this produces a new error on start:

    An unexpected error occured caused by exception BeanDefinitionStoreException:
    Unexpected exception parsing XML document from resource loaded through SAX InputSource; 
    nested exception is java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

I can see from the play dependencies —sync output that the inclusion of JDOM causes some changes to other dependencies, and suspect that to be the cause of the subsequent error.

Rather than continuing to guess, I’m submitting this in hopes that someone with a working build might share a combination of dependencies that will get along.

**Comment by gadkrumholz** [comment]
Hi Drew,

We have not run into this on any of our Vireo installations. We also did not have to modify the dependencies to get it to work.

Have you tried running the following play framework command? **play dependencies --sync --clearcache --%test**

Are you making sure to be using Play framework 1.3.x?

This is the line we get when we sync dependencies (and it downloads jdom 1.1.2):
**downloaded https://repo1.maven.org/maven2/org/jdom/jdom/1.1.2/jdom-1.1.2.jar**

Also, we are running with Java 7 or 8 and have tested using only the official Oracle JVM's... not sure if this would impact anything.

Thanks.

**Comment by dheles** [comment]
Thanks for the response, Gad.

I am running Play 1.3.1 and Java 7.

I'm confused as to why when you run **play dependencies --sync --clearcache --%test**, you get jdom 1.1.2, but when I run it, I get no jdom at all (and therefore the aforementioned errors). Since it is not explicitly listed in dependencies.yml, I'm guessing it is brought in as a dependency of a direct dependency. If that is the case, can you tell which one? That may help me figure out what's going wrong. 

Any other ideas welcomed.

Thanks,
-drew

**Comment by dheles** [comment]
For the sake of it, I went back and dropped Play 1.3.1 in favor of your 1.3.0 release, cleared out lib, and resynced play dependencies, but that didn't give me JDOM either...

**Comment by gadkrumholz** [comment]
that's totally weird... for sanity sake, I'll paste what I see when I sync my Vireo (maybe it can expose the problem):
=============================================================================
~/play_framework/play1/play dependencies --sync --clearcache --%test
~        _            _ 
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/   
~
~ play! 1.3.x-1.3.0-37-g2ca9290, https://www.playframework.com
~ framework ID is test
~
~ Clearing cache : /home/gad/.ivy2/cache,
~
~       Clear
~
~ Resolving dependencies using /home/gad/work/git/Vireo-Github/conf/dependencies.yml,
~
~ 	play->spring 1.0.3 (from playContributedModules)
~ 	org.springframework->spring-core 3.1.1.RELEASE (from mavenCentral)
~ 	org.springframework->spring-asm 3.1.1.RELEASE (from mavenCentral)
~ 	net.sf.jopt-simple->jopt-simple 3.0 (from mavenCentral)
~ 	org.apache.ant->ant 1.7.0 (from mavenCentral)
~ 	org.apache.ant->ant-launcher 1.7.0 (from mavenCentral)
~ 	org.springframework->spring-beans 3.1.1.RELEASE (from mavenCentral)
~ 	org.springframework->spring-context 3.1.1.RELEASE (from mavenCentral)
~ 	org.springframework->spring-aop 3.1.1.RELEASE (from mavenCentral)
~ 	org.springframework->spring-expression 3.1.1.RELEASE (from mavenCentral)
~ 	org.codehaus.jsr166-mirror->jsr166 1.7.0 (from mavenCentral)
~ 	play->less 0.9.1 (from playContributedModules)
~ 	org.apache.lucene->lucene-core 3.6.0 (from mavenCentral)
~ 	org.swordapp->sword-common 1.1 (from mavenCentral)
~ 	commons-httpclient->commons-httpclient 3.1 (from mavenCentral)
~ 	javax.servlet->servlet-api 2.4 (from mavenCentral)
~ 	org.jdesktop->swing-worker 1.1 (from mavenCentral)
~ 	xom->xom 1.1 (from mavenCentral)
~ 	xerces->xmlParserAPIs 2.6.2 (from mavenCentral)
~ 	xerces->xercesImpl 2.6.2 (from mavenCentral)
~ 	xalan->xalan 2.7.0 (from mavenCentral)
~ 	xml-apis->xml-apis 2.0.2 (from mavenCentral)
~ 	net.sf.opencsv->opencsv 2.3 (from mavenCentral)
~ 	org.apache.poi->poi 3.10-FINAL (from mavenCentral)
~ 	org.apache.poi->poi-ooxml 3.10-FINAL (from mavenCentral)
~ 	org.apache.poi->poi-ooxml-schemas 3.10-FINAL (from mavenCentral)
~ 	org.apache.xmlbeans->xmlbeans 2.3.0 (from mavenCentral)
~ 	stax->stax-api 1.0.1 (from mavenCentral)
~ 	play->qunit 1.0 (from playContributedModules)
~ 	edu.tamu.mock->mock-swordserver 1.3 (from TAMU Releases)
~ 	org.jdom->jdom 1.1.2 (from mavenCentral)
~ 	org.mortbay.jetty->jetty 6.1.5 (from mavenCentral)
~ 	org.mortbay.jetty->jetty-util 6.1.5 (from mavenCentral)
~ 	org.mortbay.jetty->servlet-api-2.5 6.1.5 (from mavenCentral)
~ 	play->db 1.1.1 (from playContributedModules)
~ 	net.sf.oval->oval 1.82 (from mavenCentral)
~
~ Downloading required dependencies,
~
~ 	downloaded https://www.playframework.com/modules/spring-1.0.3.zip                          
~ 	downloaded https://www.playframework.com/modules/less-0.9.1.zip                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/lucene/lucene-core/3.6.0/lucene-core-3.6.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/lucene/lucene-core/3.6.0/lucene-core-3.6.0-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/swordapp/sword-common/1.1/sword-common-1.1-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/swordapp/sword-common/1.1/sword-common-1.1.jar                          
~ 	downloaded https://repo1.maven.org/maven2/net/sf/opencsv/opencsv/2.3/opencsv-2.3-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/poi/poi/3.10-FINAL/poi-3.10-FINAL-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/poi/poi/3.10-FINAL/poi-3.10-FINAL.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/3.10-FINAL/poi-ooxml-3.10-FINAL-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/3.10-FINAL/poi-ooxml-3.10-FINAL.jar                          
~ 	downloaded https://www.playframework.com/modules/qunit-1.0.zip                          
~ 	downloaded https://maven.library.tamu.edu/content/repositories/releases/edu/tamu/mock/mock-swordserver/1.3/mock-swordserver-1.3.jar                          
~ 	downloaded https://www.playframework.com/modules/db-1.1.1.zip                          
~ 	downloaded https://repo1.maven.org/maven2/net/sf/oval/oval/1.82/oval-1.82-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/net/sf/oval/oval/1.82/oval-1.82.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-core/3.1.1.RELEASE/spring-core-3.1.1.RELEASE-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-core/3.1.1.RELEASE/spring-core-3.1.1.RELEASE.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-beans/3.1.1.RELEASE/spring-beans-3.1.1.RELEASE.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-beans/3.1.1.RELEASE/spring-beans-3.1.1.RELEASE-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-context/3.1.1.RELEASE/spring-context-3.1.1.RELEASE.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-context/3.1.1.RELEASE/spring-context-3.1.1.RELEASE-sources.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-asm/3.1.1.RELEASE/spring-asm-3.1.1.RELEASE.jar                          
~ 	downloaded https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/3.0/jopt-simple-3.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/ant/ant/1.7.0/ant-1.7.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.7.0/ant-launcher-1.7.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-aop/3.1.1.RELEASE/spring-aop-3.1.1.RELEASE.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/springframework/spring-expression/3.1.1.RELEASE/spring-expression-3.1.1.RELEASE.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/codehaus/jsr166-mirror/jsr166/1.7.0/jsr166-1.7.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar                          
~ 	downloaded https://repo1.maven.org/maven2/javax/servlet/servlet-api/2.4/servlet-api-2.4.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/jdesktop/swing-worker/1.1/swing-worker-1.1.jar                          
~ 	downloaded https://repo1.maven.org/maven2/xom/xom/1.1/xom-1.1.jar                          
~ 	downloaded https://repo1.maven.org/maven2/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar                          
~ 	downloaded https://repo1.maven.org/maven2/xerces/xercesImpl/2.6.2/xercesImpl-2.6.2.jar                          
~ 	downloaded https://repo1.maven.org/maven2/xalan/xalan/2.7.0/xalan-2.7.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml-schemas/3.10-FINAL/poi-ooxml-schemas-3.10-FINAL.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/2.3.0/xmlbeans-2.3.0.jar                          
~ 	downloaded https://repo1.maven.org/maven2/stax/stax-api/1.0.1/stax-api-1.0.1.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/jdom/jdom/1.1.2/jdom-1.1.2.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/mortbay/jetty/jetty/6.1.5/jetty-6.1.5.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/mortbay/jetty/jetty-util/6.1.5/jetty-util-6.1.5.jar                          
~ 	downloaded https://repo1.maven.org/maven2/org/mortbay/jetty/servlet-api-2.5/6.1.5/servlet-api-2.5-6.1.5.jar                          
~
~ Some dependencies have been evicted,
~
~	log4j 1.2.15 is overriden by log4j 1.2.17
~	jaxen 1.1.3 is overriden by jaxen 1.1
~	commons-fileupload 1.2 is overriden by commons-fileupload 1.3
~	log4j 1.2.13 is overriden by log4j 1.2.17
~	jaxen 1.1-beta-8 is overriden by jaxen 1.1
~	oval 1.84 is overriden by oval 1.82
~	commons-logging 1.0.4 is overriden by commons-logging 1.1.3
~	ehcache-core 2.0.0 is overriden by ehcache-core 2.6.9
~	commons-codec 1.2 is overriden by commons-codec 1.8
~	commons-logging 1.1 is overriden by commons-logging 1.1.3
~	commons-io 1.3.1 is overriden by commons-io 2.4
~	commons-logging 1.1.1 is overriden by commons-logging 1.1.3
~	commons-codec 1.5 is overriden by commons-codec 1.8
~
~ Installing resolved dependencies,
~
~ 	modules/spring-1.0.3
~ 	modules/less-0.9.1
~ 	lib/lucene-core-3.6.0.jar
~ 	lib/sword-common-1.1.jar
~ 	lib/opencsv-2.3.jar
~ 	lib/poi-3.10-FINAL.jar
~ 	lib/poi-ooxml-3.10-FINAL.jar
~ 	modules/qunit-1.0
~ 	lib/mock-swordserver-1.3.jar
~ 	modules/db-1.1.1
~ 	lib/oval-1.82.jar
~ 	lib/spring-core-3.1.1.RELEASE.jar
~ 	lib/spring-beans-3.1.1.RELEASE.jar
~ 	lib/spring-context-3.1.1.RELEASE.jar
~ 	lib/spring-asm-3.1.1.RELEASE.jar
~ 	lib/jopt-simple-3.0.jar
~ 	lib/ant-1.7.0.jar
~ 	lib/ant-launcher-1.7.0.jar
~ 	lib/spring-aop-3.1.1.RELEASE.jar
~ 	lib/spring-expression-3.1.1.RELEASE.jar
~ 	lib/jsr166-1.7.0.jar
~ 	lib/commons-httpclient-3.1.jar
~ 	lib/servlet-api-2.4.jar
~ 	lib/swing-worker-1.1.jar
~ 	lib/xom-1.1.jar
~ 	lib/xmlParserAPIs-2.6.2.jar
~ 	lib/xercesImpl-2.6.2.jar
~ 	lib/xalan-2.7.0.jar
~ 	lib/poi-ooxml-schemas-3.10-FINAL.jar
~ 	lib/xmlbeans-2.3.0.jar
~ 	lib/stax-api-1.0.1.jar
~ 	lib/jdom-1.1.2.jar
~ 	lib/jetty-6.1.5.jar
~ 	lib/jetty-util-6.1.5.jar
~ 	lib/servlet-api-2.5-6.1.5.jar
~
~ Done!
~

**Comment by dheles** [comment]
Ok. That was helpful, thanks. I think I see the problem now. Somewhere along the line, the two dashes before the %test argument got mangled, so when I ran play dependencies, it reported:
    ~ WARNING: —-%test argument will be skipped
(note the funky "—-", it's a lot easier to spot here than in my terminal...)
Between cutting and pasting from my notes and rerunning previously run commands in my terminal, this proved to be a very persistent typo for me. Additionally, the environment I have been working on is %dev and I had never (before today) [set the framework id](https://www.playframework.com/documentation/1.3.x/ids#id) to %test. Between these factors, I wasn't getting the dependencies marked "id: test" in the .yml file, apparently one of which is responsible for bringing in JDOM.

I might suggest that since JDOM is required by non-test code (in /app/org/tdl/vireo/services/Utilities.java), that it (or perhaps the direct dependency that brings it to the dance), be treated as a non-test dependency. Otherwise, it will continue to be necessary to sync dependencies with the --%test argument in all environments (including production).

At any rate, thanks for your help in resolving this.

**Comment by gadkrumholz** [comment]
Closing issue.
