### ISSUE TITLE
Problem in installing Vireo 4.x using Vagrant virtubalbox

### ISSUE THREAD

**Issue by taozhaolib** [TexasDigitalLibrary/Vireo#687]
Hi fellows, this is developer Tao from OU libraries:

Installed and ran in a Centos 7 vagrant box. Ran spring boot with port 9000. Forwarded the port to host machine and at Chrome and Firefox. 
The page could not be loaded correctly:

![image](https://user-images.githubusercontent.com/7934682/34912359-44860076-f8a5-11e7-9fbb-740052e70582.png)

The console has errors:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/7934682/34912378-a935873a-f8a5-11e7-85d9-beec343b7860.png">

Please let me know if you need more information.

**Comment by jeremythuff** [comment]
There is currently a ([PR](https://github.com/TexasDigitalLibrary/Vireo/pull/683)) to address this issue. Checking out that branch should give you a version of Vireo that does not exhibit that behavior. I imagine this PR will be soon.

**Comment by taozhaolib** [comment]
Thanks!
