### ISSUE TITLE
Organizations not deleting in some circumstances

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#721]
If a child is customized before a parent, the child organization does not always delete if needed. 
I accidentally customized a parent after I created a "child 1" workflow.  I thought I was on "child 2" workflow and not the parent. (not at Institution Level btw)   Child 2 organization was deleted. Child 1 will not delete.  I tested the theory on TAMU demo and reproduced the behavior.

**Comment by cstarcher** [comment]
Unable to reproduce in version 4.2.7.
