### ISSUE TITLE
Controlled vocabularies should have an option to alphabetize themselves.

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#758]

**Comment by jcreel** [comment]
Assume for sizing that all CVs will be sorted by vocabulary word

**Comment by jcreel** [comment]
Quick look at client side JS indicates this is done - need to check before closing.

**Comment by wwelling** [comment]
Controlled vocabulary words are alphabetized in application settings and via typeahead when filling out field profile.
