### ISSUE TITLE
On admin view tab, when changing type of uploaded file but canceling, it shows in the UI even after modal is closed

### ISSUE THREAD

**Issue by jcreel** [TexasDigitalLibrary/Vireo#799]
When a different file type is selected, i.e. switching from LICENSE to SUPPLEMENTAL, the file listing table updates the field.  When the modal is cancelled, the file listing still shows the updated value.  It is not persisted (which is a good thing), and shows the correct value on page reload.

**Comment by wwelling** [comment]
unable to reproduce
