### ISSUE TITLE
Clear query params on navigation

### ISSUE THREAD

**Issue by wwelling** [TexasDigitalLibrary/Vireo#817]

**Comment by nwoodward** [comment]
For clarification, are these the query params referred to in this issue? 
![search-filters](https://user-images.githubusercontent.com/1099753/37414200-95f9145c-2776-11e8-91f2-d9f9ada424db.jpg)

Any others?

**Comment by wwelling** [comment]
No. It is referring to the URL query parameters. They will clear for some navigations. The case in which I reported this was for application settings. If you open an accordion pane it will add a query param. Any navigation should remove them. This is likely at the tab navigation level.

This issue is rather low priority.

**Comment by nwoodward** [comment]
Ah, OK. Context is missing from some of these bugs, so I'm trying to figure out where they are. I'll leave this one alone.

**Comment by wwelling** [comment]
Yeah, that is most likely. I will make an attempt to be more specific in the issues. Sometimes you have to generalize in order to cover across an application.

**Comment by nwoodward** [comment]
Is there a priority queue?

**Comment by wwelling** [comment]
I use the next column on the waffle board. https://waffle.io/TexasDigitalLibrary/Vireo?utm_source=badge

We could create tags for low, medium, and high priority. There is already a very low priority tag called ice box.

**Comment by nwoodward** [comment]
I see what you mean now. If I click around in the Settings accordions and then click on the List tab then they disappear. But if I click on the View tab, they stick around. The link for List is an href="/admin/list", while View is ng-click="viewSelect()". View seems to be the only navigation away from Settings where they stick around.
