### ISSUE TITLE
Display error message at point of error, not at Confirm & Submit

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#853]
Please change Vireo 4 to behave like Vireo 3 in regard to error notices  (ie a required field was skipped, the wrong format was used, etc.)  Several testers noted that they would like this functionality returned to the way it was in Vireo 3 and not wait until the Confirm & Submit page to learn there are errors that need to be corrected.

**Comment by jcreel** [comment]
Do we need to prevent navigation away from the page if any fields aren't valid?

**Comment by StephanieVUGSC** [comment]
No, Vireo 3 allows navigation away from the page.

**Comment by jcreel** [comment]
Vireo 4 should be validating fields on blur.  Double check that this is working.
