### ISSUE TITLE
File upload problems in Student Interface

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#855]
Stephanie was able to replicate some of the file upload problems in TAMU demo site 2:55, 3-19-18.  I was unable to upload a 1.2MB file as a Source or Administrative file.    After 30 seconds of waiting for the upload to complete, I moved to another tab.  I went back and the file was still uploading, but other beta testers reported that their file was missing when they went back to the screen.

**Comment by jcreel** [comment]
Duplicates 827

**Comment by wwelling** [comment]
There error handling is not complete and it does not report that the file has failed and the progress bar is never disabled.
This gives the false impression that the file is still uploading.

@kaladay
