### ISSUE TITLE
Accessiblility issue - file upload

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#856]
NOTE, this may extend beyond example provided. 
ACCESSIBILITY: Tt does not appear to be possible to complete the "File Upload" form using only keyboard input, as the upload fields are not tabbable

**Comment by kaladay** [comment]
Resolved in #862.

**Comment by kaladay** [comment]
There is a "File Upload" form under _Organizations and Workflows_ that has not been addressed in #862.

**Comment by StephanieVUGSC** [comment]
I have confirmed this fix. Approved.
