### ISSUE TITLE
Usability issue: Student interface, Confirm and Submit page, file names

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#857]
USABILITY: I (Drew Heles) think it would be preferable if the filenames on the "File Upload" section of the "Confirm & Submit" form could appear as the filenames I provided, rather than paths like "private/767048437/1520608718950-HELES-Dissertation.pdf"

**Comment by jcreel** [comment]
The files are renamed  when they're saved on disk. Would it be helpful enough to remove the path and the timestamp?

**Comment by StephanieVUGSC** [comment]
First, removing the path and timestamp would be great. 
Second, I misread this comment from the beta tester.  I think he is saying to keep the original file name (although he provided a file name similar to Vireo 3).   We had more comments about keeping file naming the same as Vireo 3. Changing the format will impact multiple workflows. I'm copying other tester feedback below.   

Regarding "review note on changing name format during student submission (per youtube request):  Yes, this is a very helpful feature of the current version of Vireo.  When students submit documents, Vireo automatically re-formats the document titles.  This provides a nice uniformity that is easy for reviewers, students, and faculty to follow. "

"Active Document does not rename. In Vireo 3, it automatically renames as Last Name-Document type-Year. "

**Comment by jcreel** [comment]
Double check current status of file-rename on upload in Vireo 4 master.

**Comment by StephanieVUGSC** [comment]
I reached out to several users from large institutions this morning for feedback.  The consensus is to leave the naming convention the same as Vireo 3, which is  LASTNAME-DOCUMENTTYPE-GRADUATION YEAR.    Note that Vireo 4 is currently pulling the year from when it was submitted, not the year selected  for Graduation date. 

Why it is important....
"I have different sets of emails I send to master’s vs. doctoral students when I’m checking in an ETD, and having dissertation in the file name tells me quickly which particular email I need to send to the student. Given the short amount of time in which I’m sending lots of emails, it seems a small thing, but I think it would quickly become irritating not to have that at a glance."

"We have a rollover deadline every semester, and for the fall-rolling-to-spring, I literally would have to change them all to the following year – for example, they submit by Dec 6 to be a May 2019 grad but be exempt from enrolling in spring dissertation hours...if Vireo pulls submission year then I would have to change all of those, one by one."
