### ISSUE TITLE
Immediately close student submission at Confirm & Submit

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#858]
There is a slight lag in the change of status between In Progress and Submitted when a students hits Confirm & Submit.    Either shorten the lag time or close the submission to corrections when Confirm & Submit button is hit.    Beta tester (and SL) were able to edit a submission by clicking on the "View submission status" link at the bottom of the confirmation page.  
![image](https://user-images.githubusercontent.com/35782552/37620754-21464594-2b8b-11e8-9612-33a370b6886a.png)

The submission status was still In Process.  Advisor email will be sent twice if student hits "Confirm & Submit" again.  I changed my title during that short time to confirm the email behavior.

**Comment by jcreel** [comment]
Hide the link until successful callback

**Comment by kaladay** [comment]
The Submit button is disabled during submit.
The Submission Complete page is never redirect to until after submit is complete.
This specific case may already be resolved.

I thought about the ability to change values while waiting for submit to complete.
During this lag time, I can navigate between the workflow navigation tabs, such as selecting *1. Personal Information* and then change those values before submit is completed.

This can be solved by disabling those navigation buttons while submitting.
