### ISSUE TITLE
Simplify Customize View in List screen - Staff interface

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#859]
Several beta testers had trouble with moving fields from Disabled to Displayed columns.   Suggestions to improve:  shorten the list; allow a more effortless way to drag and drop; move the Save button to the top of the window.

Comments from testers -

Customize view: When moving the Customize Results Table fields around - it is very difficult to move a field that is near the end of the grey list over to the green list in one move. I have to inch it up until the green list comes into view then move it over. 

When using the "Customized View" function, if the item to be moved from the "gray" side to the "green" side is in the lower part of the "gray" list, it's not possible to grab it and move it up to the "green" area without moving it up in the "gray" area until the "green" area displays. If the item is grabbed to be moved, the display needs to move up and down more effectively.  

Under customize view: that table has gotten so long with so many options. Can we please move (or add) a Save button to the top of that list? This is not an issue in Vireo 3 because there are only a few options so everything shows up without having to scroll. Also, when trying to move Submission Type from Disabled Columns over to the Displayed Columns side, that variable was near the bottom of the list, but the displayed columns list was quite short, so I had to drag the variable up to move it. The only problem with that was the screen wouldn't scroll. I'd get to the top of what was showing and it wouldn't move further, so I'd have to drop that variable in that place of the disabled columns view, scroll up to show more of the screen, and drag it up until I actually saw the Displayed columns portion where I could then move it and drop it. If this new filters table is going to be this long, the screen needs to scroll up while trying to drag variables that are at the bottom of the list to the displayed columns side (until it's visible on the screen).

In the Customize Filters view, I discovered if I scrolled to the bottom of the list, I could see the Save and Clear buttons. If I started to scroll up, those buttons sat in a separate frame not in the same window. But as soon as I get near the top to that listing, they disappear, and are only accessible if I scroll completely to the bottom of the list. They need to stay visible all the way to the top of that list.

**Comment by jcreel** [comment]
Add some arrow buttons on each of the fields to easily transition them from side to side.
Make sure Save and Clear buttons stay visible at all times in the modal.
