### ISSUE TITLE
Accessibility Issue : tab order

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#862]
Tab   order does not work as expected on all forms. e.g. on the "Document   Information" form, you can't tab from "Defence Date" to   "Submission Type". In fact, it does not appear to be possible to   tab to any of the dropdown fields. This is an accessibility issue.

**Comment by jcreel** [comment]
Ensure that all DOM elements for input are buttons or links or other tab-able entity.

**Comment by jcreel** [comment]
Need to add cross-browser support for highlighting in FireFox.

**Comment by kaladay** [comment]
This highlighting appears to be added by the webkit-based browser itself.
That is to say, a user-agent feature is causing the highlighting and there is no code within our code base doing this.

**Comment by StephanieVUGSC** [comment]
I have confirmed this fix. Approved.
