### ISSUE TITLE
Bug in Previously Published checkbox - Student Interface

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#866]
When clicking on the checkbox after inputting info for previously published material, the text that was input disappears.  In addition, checking and unchecking the box more than once makes the field profile duplicate itself.

**Comment by jcreel** [comment]
The first part of this was intended behavior - do we need to iterate on this for a different UX?  Could we just provide some warning text?  We should also double-check how Vireo 3 does this.
For the second part, it sounds like a null id is being sent resulting in a new field profile.

**Comment by rladdusaw** [comment]
Vireo 3 does not clear the text if you uncheck the box, but will not persist the text unless the checkbox is checked when the page is saved.

Vireo 4 saves the field When you click the checkbox or click away from the field, which saves it without the text if the checkbox is unchecked. It's effectively saving the field the same way, the user experience is just a little different.
