### ISSUE TITLE
INPUT_CONTACT does not throw error when email address is missing

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#867]
When the field profile is set to "required" and the Input Type is set to "INPUT_CONTACT" there is no error produced if you do not fill out the email address.  This is a problem because with no email, the advisor/chair will not receive any auto generated emails.

**Comment by jcreel** [comment]
Needs a client side validator

**Comment by kaladay** [comment]
#946 introduces the use of INPUT_CONTACT and may need to be considered when resolving this.

**Comment by kaladay** [comment]
Weaver-Wevservice-Core has been modified in regards to this.
see: https://github.com/TAMULib/Weaver-Webservice-Core/pull/88 .

**Comment by StephanieVUGSC** [comment]
I have confirmed this fix. Approved.
