### ISSUE TITLE
Input values from student side appear in wrong field profile on staff side on occasion

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#869]
See image.  The data for the field profiles is jumbled in the staff View. 
![image](https://user-images.githubusercontent.com/35782552/38043977-143f8398-327e-11e8-8a2a-231dce2c381c.png)

**Comment by jcreel** [comment]
Attempt to reproduce

**Comment by kaladay** [comment]
Able to reproduce under the same or similar conditions that I described in #868.
I suspect this is the same problem as #868, but manifesting in a different way.
