### ISSUE TITLE
Committee Member Role Types in Vireo 3 are missing from 4

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#870]
The ability to create role types is missing from Vireo 4.
![image](https://user-images.githubusercontent.com/35782552/38044702-2d8c6058-3280-11e8-9511-bf970cb5f559.png)

**Comment by StephanieVUGSC** [comment]
Reviewer comments:
 in Vireo 3, when we're making a change to committee, there is a spot for us to designate the role - sometimes the students get it wrong, and we have to correct that information (and yes, sometimes they actually do put the wrong person as their chair). We have to be able to have Co-Supervisors designated, that is part of the meta data we put into our repository. If I add someone to the committee, again, there's no place for me to put their committee role. We need that functionality (which we currently have). 

Under Document Information tab --> Committee Members, it is very confusing and difficult to realize that the committee members should be name and then role. Instead, it looks like it should just be a list of committee members. Also, I don't see a space for co-chair.

**Comment by jcreel** [comment]
It may be possible to accommodate the use case with a creative use of new field profiles/predicates.  We need to propose this and collect more requirements before sizing the feature.

**Comment by StephanieVUGSC** [comment]
This issue can be closed.   I let the chair/advisor field be repeatable and found that both received the initial submission emails.  They both appear in the submission and both (theoretically) are exported in the metadata files.  It failed with my DSpaceSimple export but there was a note in the field that confirmed that it was meant to display both “<!—dc.contributor.advisor=Committee Members who are flagged as chair (may be multiple) --> 

The other Reviewer concerns have been addressed with bug fixes and improvements to the staff interface.
