### ISSUE TITLE
Strictly enforce controlled vocabulary for committee fields

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#871]
The input type "INPUT_CONTACT" allows free text, "INPUT_TEXT_WITH_DEFINITION" does not provide an email field, and "INPUT_SELECT" does not provide an email field so there are no options for controlled list of names _with_ emails for the Chair or committee members.

**Comment by wwelling** [comment]
Communicate with product owner to ensure implemented correct.
