### ISSUE TITLE
Change submit button to "Corrections Completed"

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#885]
Student Interface. Needs Correction view.  Change the button "Submit Corrections" to "Corrections Received" to match the text of the instruction box and to be the same as Vireo 3. 

![image](https://user-images.githubusercontent.com/35782552/39710948-e08b2c0c-51e3-11e8-93b6-916659f02d58.png)

**Comment by jcreel** [comment]
Bring up Vireo 3 and make it look the same.

**Comment by StephanieVUGSC** [comment]
Does not appear in https://vireodemo.library.tamu.edu/  on 07/03/2018 12:39

**Comment by cstarcher** [comment]
This issue was resolved.

PR #944
