### ISSUE TITLE
Pop-up on hover is delayed or does not display

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#886]
Student Interface.  When hovering over the "info" icon in the student submission screen it would be helpful to have the pope up appear just a fraction of a second sooner.  Currently nothing happens immediately, so I click on the "info" icon.  Clicking on it, just makes the pop up show for a millisecond.  It is difficult for user to know how to see the pop-up.  In addition, sometimes the pop up will cease displaying if you return to it and hover.  Then after a few seconds it will start working again with the slightly delayed pop up.

**Comment by jcreel** [comment]
Let's switch to bootstrap ui for the tooltips and we should get cleaner functionality.

**Comment by jcreel** [comment]
Duplicates #764
