### ISSUE TITLE
Need HTML link for ORCID registration

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#887]
Student Interface.  In Vireo 3, there is a hyperlink for students to easily link out to ORCID and claim their ID.  In Vireo 4, the URL is provided in the info icon pop-up but it is not hyperlinked, so it is unusable.  Please add the text and hyperlink from Vireo 3. 
![image](https://user-images.githubusercontent.com/35782552/39720449-03d3de66-5202-11e8-9f06-c6b356218d24.png)

**Comment by jcreel** [comment]
Size this as a one-off fix on the ORCID input type.  Let's fix it also for the ProQuest field while we're at it.
