### ISSUE TITLE
Update sticky note for SIZE Quota

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#889]
Student Interface.  Sticky Note for SIZE Quote on File Upload tab is no longer in sync with the measurement used on uploaded file.  Please ask TDL for maximum size in bytes for a single file, and maximum size in bytes for total files and update sticky note.

**Comment by wwelling** [comment]
Maximum single file upload is configurable. There is no constraint for maximum size of all files upload either per user or per submission.

**Comment by StephanieVUGSC** [comment]
OK,  please change this request to "Remove the  sizeQuota note from the code"
