### ISSUE TITLE
Emails sent from Vireo should be included in Action Log

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#892]
As an Administrator I need to quickly determine if we emailed a notice to a student or chair.  

Please log all emails sent from Vireo in the submission Action log, as they are in Vireo 3.    See image from Vireo 3, followed by image from Vireo 4.  The log in Vireo 4 should begin with "Email sent to: [ recipient@school.edu ]" 

![image](https://user-images.githubusercontent.com/35782552/39725828-ae43540c-5212-11e8-85fb-21ea48170066.png)

![image](https://user-images.githubusercontent.com/35782552/39725861-cb303bf2-5212-11e8-9ff8-2523168f56d3.png)

**Comment by jcreel** [comment]
Submitter's email is being logged when the message is sent to the advisor instead of the advisor's email.

**Comment by cstarcher** [comment]
It seems Vireo 3 only logs emails in the action log sent from the Add Comment and Add File modals. I wanted to clarify before moving forward with this issue that the added functionality to log emails sent from the Generate Advisor Email button and email workflow rules was desired.
