### ISSUE TITLE
Bug: Assigned To "Unassigned"

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#897]
Staff Interface. List View. 

There are two problems occurring when "Unassigned" is selected in the ASSIGNED TO field.  First, the list is not filtered for submissions with no assignments.  Instead, all submissions disappear from view.  Second,  clicking on the X to the left of Unassigned under "Now Filtering By" does not remove it.  Normally that X will remove the term from the filter.

**Comment by kaladay** [comment]
This relates to #879 .

**Comment by kaladay** [comment]
This also relates to #899.

**Comment by kaladay** [comment]
This is broken by https://github.com/TexasDigitalLibrary/Vireo/commit/0e6dc80103bf280b4ed8411bffaf80ceaa9e5792#diff-08a1b2c23b6a9450dc5e40d017e47601R193.

`null` is a valid filterValue.
The toString() behavior needs to be relooked at in #932.
