### ISSUE TITLE
BUG: "Custom actions" column does not work in List View

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#901]
When the custom actions column is included in a customized view, it does not contain information.  This column needs to work the same as it does in Vireo 3, where all custom actions are listed and checkboxes indicate what has been completed.  This feature is important members.

Vireo 3 screenshot 
![image](https://user-images.githubusercontent.com/35782552/39766844-e3b9ca9c-52aa-11e8-8a75-b0f65255480a.png)

--

**Comment by StephanieVUGSC** [comment]
Does not appear in https://vireodemo.library.tamu.edu/ on 07/03/2018 12:43

**Comment by wwelling** [comment]
this is implemented and working on sprint32
