### ISSUE TITLE
BUG: Custom actions filter has no effect.

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#902]
Staff Interface. List View. 
When "Custom actions" is added to the list of filters, it shows up in the sidebar, but clicking on the links for the actions does nothing.  This field is used by members and needs to work the same as it does in Vireo 3, where a selected custom actions will filter the list for that action if the box is checked.  See Vireo 3 screen as example. 

![image](https://user-images.githubusercontent.com/35782552/39767358-2a2c2370-52ac-11e8-841a-131fa4b96a74.png)

**Comment by jcreel** [comment]
- Within admin submission view, the checkbox for custom actions is not persisting
- In the list view, the custom actions aren't adding to the filter
- Need to implement the custom action list in the cell - maybe editable inline?
