### ISSUE TITLE
Submission List Query broken after changing logic on filter to "AND"

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#907]
Staff Interface. List View. 

Currently the logic of the filters in List View works as "OR" statements.  It need to be AND.  See attached example of OR - where filter shows a two year embargo and Dissertation submission type.  If the filter worked as "AND" there should be no results.
![image](https://user-images.githubusercontent.com/35782552/40063533-2a9d5c1c-5823-11e8-8504-77d8e7602d58.png)

**Comment by jcreel** [comment]
Typical behavior for filters would be OR within columns and AND across columns.  We were under the impression that Vireo 3 was doing OR across columns, so we'll need to double check.  Sized according to having to change the boolean logic in the SQL query.

**Comment by StephanieVUGSC** [comment]
Stephanie checked logic.  Confirmed that it is AND across columns and OR within a column.

**Comment by StephanieVUGSC** [comment]
Please move issue to Next column.

**Comment by jcreel** [comment]
Full-text search is not working in the current build.

**Comment by StephanieVUGSC** [comment]
If this is in reference to the general "Search Box" I don't believe it was working for quite some time.  Please see #1146 for request to hide the "Search Box"  With all the other filters, it is unnecessary to have this option.  Request is to hide instead of remove from code in case there is a desire to develop it in the future, but please do whatever is best.
