### ISSUE TITLE
BUG: Clear Current Filter does not move criteria out of filter

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#908]
Staff Interface. List View.

Choosing the "Clear current filter" option will change the list of results, but the criteria of the filter stay under "Now Filtering By"

**Comment by jcreel** [comment]
Unable to reproduce on a couple of machines - unable to size for now.

**Comment by wwelling** [comment]
Let's try to reproduce one more time and close if not able to.

**Comment by StephanieVUGSC** [comment]
Unable to produce on TDL site. 8/28/2018

**Comment by wwelling** [comment]
unable to reproduce
