### ISSUE TITLE
Embargo options not visible in Advisor (Chair) interface

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#910]
Advisor/Chair/Faculty interface

The embargo options should be visible in the Faculty view of the submission (as it is in Vireo 3) because he/she needs to know what other options there are if the embargo the student selected is undesirable.

**Comment by StephanieVUGSC** [comment]
Embargo options are in view.  Approved.

**Comment by StephanieVUGSC** [comment]
This problem is occurring again.  Embargos which were not selected are also not in the students "confirm and submit" view either.

**Comment by smutniak** [comment]
This appears sporadically for utswmed recently

**Comment by kaladay** [comment]
This may or may not be related, but I see errors like the following under the **Review Application** when viewing with a user with `ROLE_ADMIN`.

```
angular.js:15570 TypeError: Cannot read property 'id' of null
    at AbstractRepo.abstractRepo.contains (abstractRepo.js:40)
    at AbstractRepo.abstractRepo.add (abstractRepo.js:49)
    at abstractRepo.js:347
   ...
```

```
angular.js:15570 TypeError: $scope.isEmbargo is not a function
    at $scope.isEmbargoWrap (reviewSubmissionFieldsDirective.js:75)
    at Object.$scope.orderVocabularyWords [as get] (dictionaryWordsDirective.js:29)
    at angular.js:23852
    ...
```
