### ISSUE TITLE
BUG:  Edit icon for new email templates, opens previous template

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#912]
Staff interface.  Application Settings.  Email templates.

After creating and saving a new email template, the template which precedes the new one will open when the Edit icon is selected.    Closing the accordian or changing screens did not resolve.  However, refreshing browser will resolve.

**Comment by jcreel** [comment]
not clearing a modal

**Comment by cstarcher** [comment]
I was unable to reproduce this behavior on localhost or vireodemo.

**Comment by wwelling** [comment]
Let's try to reproduce one more time and then close if not able to.

**Comment by wwelling** [comment]
unable to reproduce
