### ISSUE TITLE
BUG:  Controlled Vocabulary editing

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#913]
Staff interface.  Application Settings.  Controlled Vocabulary Management

When manually adding or removing values from a controlled vocabulary, the system always jumps to the Colleges CV.  So for each change, you have to select the desired CV again.  Beta tester comment "If I'm working on updating a list, I'd rather it just stay put and let me navigate away from it when I'm done... I'm not a fan of software trying to guess where I want to navigate when I know better than it does what I want to do." 

Many beta testers commented on this annoying behavior.

**Comment by kaladay** [comment]
The AJAX request handler is resetting the entire Controlled Vocabulary Management section when updating. Both the Selector ("College") and Pagination states should be preserved when changing the controlled vocabulary by name settings (including changes to the sort order of the controlled vocabulary by name).

**Comment by StephanieVUGSC** [comment]
This one looks fixed to me.  It is working well.
