### ISSUE TITLE
shift second column of View tabs to the left

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#915]
Staff Interface.  View tab.  It is difficult to read the lables and values in the second column of the View tab because there is very little room and the text is wrapping/stacked on top of each other.  For  In the attached image, it is not clear what the hyphens represent.
![image](https://user-images.githubusercontent.com/35782552/40320961-18664be2-5cf3-11e8-9f90-e0f09d74ea3a.png)

**Comment by wwelling** [comment]
Each column takes up 50% of the tab container. Shifting the column over would only make values of the left column wrap sooner. The same problem would if you put the committee members in the left column. The solution in PR #1034 is to use a more bootstrap form approach where the label is above the inputs/values. This gives the values the entire half. For responsive views they will stack before to much wrapping. Also, places repeatable under its label without a gap between the first two repeatable values.
