### ISSUE TITLE
Browser related issues

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#917]
The UI in Firefox has some unfavorable behavior.  One example is in Staff Interface/Organizations & Workflows/ Manage Workflow. 

When a field profile is updated the workflow step remains open as it should, but the cursor jumps to the top of the workflow step instead of the remaining in place.   The user has to scroll down to verify that update was made or before continuing to make adjustments to settings.

**Comment by jcreel** [comment]
This is possibly addressed by fixing the duplicate id problem

**Comment by StephanieVUGSC** [comment]
Re-tested on 8/6/18.  Behavior described above is same as in Chrome, so there is no bug. However, in Firefox that Status button in left side of  View in staff mode will not update until page is refreshed, although the Status in List view appears to update immediately.
