### ISSUE TITLE
BUG:  Default Embargo filter does not appear in Now filtering by

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#921]
Staff Interface. List View.   When filtering by the Default Embargo, the list filters but it is not apparent that the list is filtered at all because it does not display consistently (sometimes it does display).  In the attached image the list is filtered for Default Embargo = Journal Hold.

![image](https://user-images.githubusercontent.com/35782552/40372139-b36bd1e6-5da9-11e8-8cc0-e3d0d7a5751a.png)

**Comment by rladdusaw** [comment]
I'm unable to reproduce this bug both locally and on Vireo demo. Can you provide the steps needed to reproduce this bug?

**Comment by wwelling** [comment]
Unable to reproduce.
