### ISSUE TITLE
ProQuest Publication filter enhancement

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#922]
Staff Interface. List View. 

When filtering a list using ProQuest Publication, the search box will accept any value.  Typing in a logibal but wrong value (ie - "unchecked") will return 0 results.  Please change the search box for this filter into a selection list of Yes and No.

**Comment by jcreel** [comment]
Need a new sidebar widget to handle booleans.  Consider applying this enhancement to other predicates.

**Comment by StephanieVUGSC** [comment]
This is fixed and working nicely
