### ISSUE TITLE
Inline Edit for Controlled Vocabulary deadlocks on duplicate names

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#939]
In administration _Application Settings_, under _Controlled Vocabulary Management_, the table near the bottom can be edited inline.

When editing inline, there appears to be some sort of duplicate name check that fails with console log errors like:
```TypeError: Cannot read property 'status' of undefined```
and
```TypeError: Cannot read property 'VocabularyWord' of undefined```

This failure causes the inline editing to become deadlocked and unclosable.
Further actions in the _Controlled Vocabulary Management_ do not work properly by having the deadlocked row always displayed until a hard reset is performed on the page.

**Comment by wwelling** [comment]
Could not reproduce.

**Comment by wwelling** [comment]
@kaladay has also confirmed this no longer occurs.
