### ISSUE TITLE
Add validation to email-related inputs in Add File modal

### ISSUE THREAD

**Issue by cstarcher** [TexasDigitalLibrary/Vireo#953]

**Comment by StephanieVUGSC** [comment]
Tested this on https://vireodemo.library.tamu.edu/ 7/03/2018
Observations:  No error messages appeared when adding text without @xxx.x
Submit button would not activate, even after providing a real email address.

**Comment by cstarcher** [comment]
Email validation and submit button functionality are working correctly on test-etd.tdl.org. I believe this issue was resolved during the last sprint but was not merged into the branch deployed on vireodemo that was tested by Stephanie.

The current functionality does not provide an error message for invalid email addresses. It disables the submit button unless a valid email address is present. This is different from Vireo 3 which does not disable the submit button but provides an error message after clicking the submit button if an email address is not present. If this functionality is desired, it should probably be a separate feature request.
