### ISSUE TITLE
Long filenames in uploaded file overflow out of sidebox

### ISSUE THREAD

**Issue by kaladay** [TexasDigitalLibrary/Vireo#958]
In the admin view, under _Document Information_ for a viewed submission, under _Submission Status_,  the _What_ action log does not wrap overly long filenames, such as `a81dabcfe1d651ed23f3860ffa343141.png`.

The _What_ section likely needs a word-break style added, or something similar.

**Comment by StephanieVUGSC** [comment]
I have confirmed this fix. Approved.
