### ISSUE TITLE
Email workflow rules no longer function in TDL site

### ISSUE THREAD

**Issue by StephanieVUGSC** [TexasDigitalLibrary/Vireo#982]
The "System Advisor Review Request" and "System Initial Submission" emails are no longer being sent on upon submission.  

I've checked and double checked the settings for Email Workflow Rules on the Institution level and something is preventing them from either being produced or sent from Vireo.   I've used mailinator accounts to confirm that the issue is not with campus security measures. 

The email problem is limited to the Workflow rules.  I can successfully "Generate Advisor Email" from the submission View.  I can also successfully send emails using "Add Comment"

**Comment by cstarcher** [comment]
I tested this on TDL site, and both emails are sent. I think this may be an issue of confusion with the glyphicon play/pause buttons. Currently, the play button shows when the rule is turned on and the pause button when the rule is turned off. This may be counterintuitive.

**Comment by cstarcher** [comment]
Questions:

1. Should the play/pause buttons be changed to function the same as Vireo 3?
2. Vireo 3 requires confirmation to change play/pause. Is this confirmation step required for Vireo 4?

**Comment by StephanieVUGSC** [comment]
I don't find the icons to be an issue because I have already documented how they function.  At this point in the development I don't believe we need to change icons or add a confirmation step.

**Comment by cstarcher** [comment]
I'm leaving this issue open for further investigation.

**Comment by cstarcher** [comment]
relates to #1094 

This issue was not caused by a problem with email workflow rules. It was caused by the status update not changing when a submission was submitted from an account with the student role; therefore, no no email workflow rules were triggered.

My inability to initially recreate this issue was the result of having submitted from an account with the admin role.
